export const DEFAULT_WORK_GUEST_PATH = "/work";
export const PATH_SEPARATOR_REGEX = /[/\\]+/;
export const OPFS_COPY_CHUNK_SIZE = 8 * 1024 * 1024;
export const OPFS_SEQUENTIAL_WRITE_BUFFER_BYTES = 8 * 1024 * 1024;
export const OPFS_SEQUENTIAL_DIRECT_WRITE_MIN_BYTES = 2 * 1024 * 1024;
