use std::{env, fs, path::Path};

use rom_weaver_app::{
    BatchHeaderFixerCommand, ChecksumCommand, Commands, CompressCommand, CompressionLevelProfile,
    ExtractCommand, ListCommand, PatchApplyCommand, PatchCommands, PatchCreateCandidatesCommand,
    PatchCreateCommand, PatchValidateCommand, ProbeCommand, RomWeaverRunOutputOptions,
    RomWeaverRunRequest, TrimCommand, patch_create_format_policy_metadata,
};
use rom_weaver_core::{
    CONTAINER_FILTER_FILE_EXTENSIONS, OperationFamily, OperationStatus,
    PATCH_FILTER_FILE_EXTENSIONS, ProgressEvent, ROM_FILTER_FILE_EXTENSIONS, ThreadBudget,
    ThreadExecution, ThreadMode,
};
use serde_json::{Map, Value, json};
use ts_rs::TS;

const TYPES_OUTPUT_PATH: &str = "packages/rom-weaver-wasm/src/generated/rom-weaver-rust-types.d.ts";
const METADATA_OUTPUT_PATH: &str =
    "packages/rom-weaver-wasm/src/generated/rom-weaver-format-metadata.ts";
const TYPES_HEADER: &str =
    "// Generated by `cargo run -p rom-weaver-typegen -- --write`.\n// Do not edit manually.\n\n";
const METADATA_HEADER: &str =
    "// Generated by `cargo run -p rom-weaver-typegen -- --write`.\n// Do not edit manually.\n\n";
const RUNTIME_ALIAS_DECLS: &[&str] = &[
    "export type RomWeaverCommand = Commands;",
    "export type RomWeaverProgressEvent = ProgressEvent;",
    "export type RomWeaverRunJsonEvent = RomWeaverProgressEvent;",
    "export type RomWeaverRunInput = RomWeaverCommand | RomWeaverRunRequest;",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Mode {
    Write,
    Check,
}

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let mode = parse_mode(env::args().skip(1).collect())?;
    let outputs = [
        GeneratedOutput {
            path: TYPES_OUTPUT_PATH,
            rendered: render_types(),
        },
        GeneratedOutput {
            path: METADATA_OUTPUT_PATH,
            rendered: render_metadata(),
        },
    ];

    match mode {
        Mode::Write => {
            for output in &outputs {
                write_output(output)?;
            }
            Ok(())
        }
        Mode::Check => {
            let mut stale_paths = Vec::new();
            for output in &outputs {
                if check_output(output)? {
                    println!("{} is up to date", output.path);
                } else {
                    stale_paths.push(output.path);
                }
            }
            if stale_paths.is_empty() {
                Ok(())
            } else {
                Err(format!(
                    "generated output is stale in {}; run `cargo run -p rom-weaver-typegen -- --write`",
                    stale_paths.join(", ")
                ))
            }
        }
    }
}

struct GeneratedOutput {
    path: &'static str,
    rendered: String,
}

fn write_output(output: &GeneratedOutput) -> Result<(), String> {
    let output_path = Path::new(output.path);
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }
    fs::write(output_path, &output.rendered)
        .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    println!("wrote {}", output_path.display());
    Ok(())
}

fn check_output(output: &GeneratedOutput) -> Result<bool, String> {
    let output_path = Path::new(output.path);
    let existing = fs::read_to_string(output_path).map_err(|error| {
        format!(
            "failed to read {} for --check (run with --write first): {error}",
            output_path.display()
        )
    })?;
    Ok(existing == output.rendered)
}

fn parse_mode(args: Vec<String>) -> Result<Mode, String> {
    match args.as_slice() {
        [flag] if flag == "--write" => Ok(Mode::Write),
        [flag] if flag == "--check" => Ok(Mode::Check),
        _ => Err("usage: rom-weaver-typegen --write | --check".to_string()),
    }
}

fn render_types() -> String {
    let config = ts_rs::Config::default();
    let mut declarations = vec![
        export_decl::<OperationFamily>(&config),
        export_decl::<OperationStatus>(&config),
        export_decl::<ThreadMode>(&config),
        export_decl::<ThreadBudget>(&config),
        export_decl::<ThreadExecution>(&config),
        export_decl::<serde_json::Value>(&config),
        export_decl::<ProgressEvent>(&config),
        export_decl::<CompressionLevelProfile>(&config),
        export_decl::<ProbeCommand>(&config),
        export_decl::<ListCommand>(&config),
        export_decl::<ExtractCommand>(&config),
        export_decl::<ChecksumCommand>(&config),
        export_decl::<CompressCommand>(&config),
        export_decl::<TrimCommand>(&config),
        export_decl::<BatchHeaderFixerCommand>(&config),
        export_decl::<PatchApplyCommand>(&config),
        export_decl::<PatchValidateCommand>(&config),
        export_decl::<PatchCreateCandidatesCommand>(&config),
        export_decl::<PatchCreateCommand>(&config),
        export_decl::<PatchCommands>(&config),
        export_decl::<Commands>(&config),
        export_decl::<RomWeaverRunOutputOptions>(&config),
        export_decl::<RomWeaverRunRequest>(&config),
    ];
    declarations.extend(RUNTIME_ALIAS_DECLS.iter().map(|decl| (*decl).to_string()));

    format!("{TYPES_HEADER}{}\n", declarations.join("\n\n"))
}

fn export_decl<T: TS>(config: &ts_rs::Config) -> String {
    let decl = T::decl(config);
    if decl.trim_start().starts_with("export ") {
        decl
    } else {
        format!("export {decl}")
    }
}

fn render_metadata() -> String {
    format!(
        "{METADATA_HEADER}{}\n\n{}\n\n{}\n",
        render_ts_const(
            "ROM_WEAVER_CREATE_PATCH_FORMAT_POLICY",
            create_patch_format_policy_value()
        ),
        render_ts_const("ROM_WEAVER_FILE_FILTERS", file_filters_value()),
        "export const ROM_WEAVER_FORMAT_METADATA = {\n  createPatchFormatPolicy: ROM_WEAVER_CREATE_PATCH_FORMAT_POLICY,\n  fileFilters: ROM_WEAVER_FILE_FILTERS,\n} as const;",
    )
}

fn render_ts_const(name: &str, value: Value) -> String {
    let rendered = serde_json::to_string_pretty(&value).expect("metadata value should serialize");
    format!("export const {name} = {rendered} as const;")
}

fn create_patch_format_policy_value() -> Value {
    let metadata = patch_create_format_policy_metadata();
    json!({
        "defaultFormat": metadata.default_format,
        "largeDefaultFormat": metadata.large_default_format,
        "limits": {
            "archiveDefaultSizeBytes": metadata.archive_default_size_limit_bytes,
            "bpsDefaultSizeBytes": metadata.bps_default_size_limit_bytes,
            "ipsSizeLimitBytes": metadata.ips_size_limit_bytes,
            "legacySizeLimitBytes": metadata.legacy_size_limit_bytes,
        },
        "aliases": alias_map(metadata.aliases),
        "formats": {
            "small": metadata.small_formats,
            "medium": metadata.medium_formats,
            "midLarge": metadata.mid_large_formats,
            "large": metadata.large_formats,
        },
        "supportedCreateFormats": unique_formats(&[
            metadata.small_formats,
            metadata.medium_formats,
            metadata.mid_large_formats,
            metadata.large_formats,
        ]),
    })
}

fn file_filters_value() -> Value {
    json!({
        "containerExtensions": CONTAINER_FILTER_FILE_EXTENSIONS,
        "patchExtensions": PATCH_FILTER_FILE_EXTENSIONS,
        "romExtensions": ROM_FILTER_FILE_EXTENSIONS,
    })
}

fn alias_map(aliases: &[(&'static str, &'static str)]) -> Value {
    let mut out = Map::new();
    for (alias, canonical) in aliases {
        out.insert(
            (*alias).to_string(),
            Value::String((*canonical).to_string()),
        );
    }
    Value::Object(out)
}

fn unique_formats(groups: &[&[&'static str]]) -> Vec<&'static str> {
    let mut out = Vec::new();
    for group in groups {
        for format in *group {
            if !out.contains(format) {
                out.push(*format);
            }
        }
    }
    out
}
