use std::{env, fs, path::Path};

use rom_weaver_app::{
    BatchHeaderFixerCommand, ChecksumCommand, Commands, CompressCommand, CompressionLevelProfile,
    ExtractCommand, ListCommand, PatchApplyCommand, PatchCommands, PatchCreateCandidatesCommand,
    PatchCreateCommand, PatchValidateCommand, ProbeCommand, RomWeaverRunOutputOptions,
    RomWeaverRunRequest, TrimCommand,
};
use rom_weaver_core::{
    OperationFamily, OperationStatus, ProgressEvent, ThreadBudget, ThreadExecution, ThreadMode,
};
use ts_rs::TS;

const OUTPUT_PATH: &str = "packages/rom-weaver-wasm/src/generated/rom-weaver-rust-types.d.ts";
const HEADER: &str =
    "// Generated by `cargo run -p rom-weaver-typegen -- --write`.\n// Do not edit manually.\n\n";
const RUNTIME_ALIAS_DECLS: &[&str] = &[
    "export type RomWeaverCommand = Commands;",
    "export type RomWeaverProgressEvent = ProgressEvent;",
    "export type RomWeaverRunJsonEvent = RomWeaverProgressEvent;",
    "export type RomWeaverRunInput = RomWeaverCommand | RomWeaverRunRequest;",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Mode {
    Write,
    Check,
}

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let mode = parse_mode(env::args().skip(1).collect())?;
    let output_path = Path::new(OUTPUT_PATH);
    let rendered = render_types();

    match mode {
        Mode::Write => {
            if let Some(parent) = output_path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
            }
            fs::write(output_path, rendered)
                .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
            println!("wrote {}", output_path.display());
            Ok(())
        }
        Mode::Check => {
            let existing = fs::read_to_string(output_path).map_err(|error| {
                format!(
                    "failed to read {} for --check (run with --write first): {error}",
                    output_path.display()
                )
            })?;
            if existing == rendered {
                println!("{} is up to date", output_path.display());
                return Ok(());
            }
            Err(format!(
                "generated types are stale in {}; run `cargo run -p rom-weaver-typegen -- --write`",
                output_path.display()
            ))
        }
    }
}

fn parse_mode(args: Vec<String>) -> Result<Mode, String> {
    match args.as_slice() {
        [flag] if flag == "--write" => Ok(Mode::Write),
        [flag] if flag == "--check" => Ok(Mode::Check),
        _ => Err("usage: rom-weaver-typegen --write | --check".to_string()),
    }
}

fn render_types() -> String {
    let config = ts_rs::Config::default();
    let mut declarations = vec![
        export_decl::<OperationFamily>(&config),
        export_decl::<OperationStatus>(&config),
        export_decl::<ThreadMode>(&config),
        export_decl::<ThreadBudget>(&config),
        export_decl::<ThreadExecution>(&config),
        export_decl::<serde_json::Value>(&config),
        export_decl::<ProgressEvent>(&config),
        export_decl::<CompressionLevelProfile>(&config),
        export_decl::<ProbeCommand>(&config),
        export_decl::<ListCommand>(&config),
        export_decl::<ExtractCommand>(&config),
        export_decl::<ChecksumCommand>(&config),
        export_decl::<CompressCommand>(&config),
        export_decl::<TrimCommand>(&config),
        export_decl::<BatchHeaderFixerCommand>(&config),
        export_decl::<PatchApplyCommand>(&config),
        export_decl::<PatchValidateCommand>(&config),
        export_decl::<PatchCreateCandidatesCommand>(&config),
        export_decl::<PatchCreateCommand>(&config),
        export_decl::<PatchCommands>(&config),
        export_decl::<Commands>(&config),
        export_decl::<RomWeaverRunOutputOptions>(&config),
        export_decl::<RomWeaverRunRequest>(&config),
    ];
    declarations.extend(RUNTIME_ALIAS_DECLS.iter().map(|decl| (*decl).to_string()));

    format!("{HEADER}{}\n", declarations.join("\n\n"))
}

fn export_decl<T: TS>(config: &ts_rs::Config) -> String {
    let decl = T::decl(config);
    if decl.trim_start().starts_with("export ") {
        decl
    } else {
        format!("export {decl}")
    }
}
