#[cfg(not(target_arch = "wasm32"))]
pub(super) const PACKS: &[(&str, &[u8])] = &[
    (
        "atari-2600.pack",
        include_bytes!("../data/identify/v1/atari-2600.pack"),
    ),
    (
        "atari-5200.pack",
        include_bytes!("../data/identify/v1/atari-5200.pack"),
    ),
    (
        "atari-7800.pack",
        include_bytes!("../data/identify/v1/atari-7800.pack"),
    ),
    (
        "atari-lynx.pack",
        include_bytes!("../data/identify/v1/atari-lynx.pack"),
    ),
    (
        "neo-geo-pocket.pack",
        include_bytes!("../data/identify/v1/neo-geo-pocket.pack"),
    ),
    (
        "neo-geo-pocket-color.pack",
        include_bytes!("../data/identify/v1/neo-geo-pocket-color.pack"),
    ),
    (
        "nintendo-64.pack",
        include_bytes!("../data/identify/v1/nintendo-64.pack"),
    ),
    (
        "nintendo-entertainment-system.pack",
        include_bytes!("../data/identify/v1/nintendo-entertainment-system.pack"),
    ),
    (
        "nintendo-game-boy.pack",
        include_bytes!("../data/identify/v1/nintendo-game-boy.pack"),
    ),
    (
        "nintendo-game-boy-advance.pack",
        include_bytes!("../data/identify/v1/nintendo-game-boy-advance.pack"),
    ),
    (
        "nintendo-game-boy-color.pack",
        include_bytes!("../data/identify/v1/nintendo-game-boy-color.pack"),
    ),
    (
        "nintendo-super-nintendo-entertainment-system.pack",
        include_bytes!("../data/identify/v1/nintendo-super-nintendo-entertainment-system.pack"),
    ),
    (
        "sega-32x.pack",
        include_bytes!("../data/identify/v1/sega-32x.pack"),
    ),
    (
        "sega-game-gear.pack",
        include_bytes!("../data/identify/v1/sega-game-gear.pack"),
    ),
    (
        "sega-master-system.pack",
        include_bytes!("../data/identify/v1/sega-master-system.pack"),
    ),
    (
        "sega-mega-drive-genesis.pack",
        include_bytes!("../data/identify/v1/sega-mega-drive-genesis.pack"),
    ),
    (
        "turbografx-16-pc-engine.pack",
        include_bytes!("../data/identify/v1/turbografx-16-pc-engine.pack"),
    ),
];
