//! Unit tests for `.dcp` ZIP parsing and entry classification.
//!
//! Builds tiny STORED-method ZIP archives in memory (no DEFLATE needed) and
//! checks the central-directory reader and manifest classifier.

use std::io::Cursor;

use crate::gdrom::GdRomFs;

use super::apply::{DcpOutput, apply_dcp};
use super::manifest::{DcpManifest, DcpOperation};
use super::read_manifest;
use super::zip::{extract_entry, read_central_directory};

/// A real VCDIFF/xdelta patch turning `b"hello old world"` into
/// `b"hello new world"`, generated by `rom-weaver patch create` (stock
/// xdelta3-style, no secondary compression). Used to exercise the delta path
/// end-to-end without depending on the file-based create handler here.
const HELLO_DELTA: &[u8] = &[
    0xd6, 0xc3, 0xc4, 0x00, 0x04, 0x11, 0x64, 0x73, 0x74, 0x2e, 0x62, 0x69, 0x6e, 0x2f, 0x2f, 0x73,
    0x72, 0x63, 0x2e, 0x62, 0x69, 0x6e, 0x2f, 0x05, 0x0f, 0x00, 0x15, 0x0f, 0x00, 0x09, 0x02, 0x01,
    0x2d, 0xe6, 0x05, 0xc7, 0x6e, 0x65, 0x77, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x16, 0x0a, 0x00,
];
const HELLO_SOURCE: &[u8] = b"hello old world";
const HELLO_TARGET: &[u8] = b"hello new world";
const IP_BIN_STUB: &[u8] = &[0u8; 16];

/// A stored (uncompressed) entry to place in a synthetic ZIP.
struct Entry<'a> {
    name: &'a str,
    data: &'a [u8],
}

fn u16(v: u16) -> [u8; 2] {
    v.to_le_bytes()
}
fn u32(v: u32) -> [u8; 4] {
    v.to_le_bytes()
}

/// One entry for the general ZIP builder: name, the bytes to store, the
/// uncompressed size, and the compression method.
struct RawEntry<'a> {
    name: &'a str,
    stored: &'a [u8],
    uncompressed_size: u32,
    crc32: u32,
    method: u16,
}

/// Build a minimal, valid ZIP from entries with explicit stored bytes, sizes,
/// and compression methods.
fn build_zip_general(entries: &[RawEntry]) -> Vec<u8> {
    let mut out = Vec::new();
    let mut centrals = Vec::new();
    let mut offsets = Vec::new();

    for e in entries {
        offsets.push(out.len() as u32);
        let name = e.name.as_bytes();
        out.extend_from_slice(&u32(0x0403_4b50));
        out.extend_from_slice(&u16(20)); // version needed
        out.extend_from_slice(&u16(0)); // flags
        out.extend_from_slice(&u16(e.method));
        out.extend_from_slice(&u16(0)); // mod time
        out.extend_from_slice(&u16(0)); // mod date
        out.extend_from_slice(&u32(e.crc32)); // crc32
        out.extend_from_slice(&u32(e.stored.len() as u32)); // compressed
        out.extend_from_slice(&u32(e.uncompressed_size)); // uncompressed
        out.extend_from_slice(&u16(name.len() as u16));
        out.extend_from_slice(&u16(0)); // extra len
        out.extend_from_slice(name);
        out.extend_from_slice(e.stored);
    }

    let cd_offset = out.len() as u32;
    for (e, &offset) in entries.iter().zip(&offsets) {
        let name = e.name.as_bytes();
        centrals.extend_from_slice(&u32(0x0201_4b50));
        centrals.extend_from_slice(&u16(20)); // version made by
        centrals.extend_from_slice(&u16(20)); // version needed
        centrals.extend_from_slice(&u16(0)); // flags
        centrals.extend_from_slice(&u16(e.method));
        centrals.extend_from_slice(&u16(0)); // mod time
        centrals.extend_from_slice(&u16(0)); // mod date
        centrals.extend_from_slice(&u32(e.crc32)); // crc32
        centrals.extend_from_slice(&u32(e.stored.len() as u32));
        centrals.extend_from_slice(&u32(e.uncompressed_size));
        centrals.extend_from_slice(&u16(name.len() as u16));
        centrals.extend_from_slice(&u16(0)); // extra
        centrals.extend_from_slice(&u16(0)); // comment
        centrals.extend_from_slice(&u16(0)); // disk start
        centrals.extend_from_slice(&u16(0)); // internal attr
        centrals.extend_from_slice(&u32(0)); // external attr
        centrals.extend_from_slice(&u32(offset)); // local header offset
        centrals.extend_from_slice(name);
    }
    let cd_size = centrals.len() as u32;
    out.extend_from_slice(&centrals);

    // End Of Central Directory.
    out.extend_from_slice(&u32(0x0605_4b50));
    out.extend_from_slice(&u16(0)); // disk
    out.extend_from_slice(&u16(0)); // cd disk
    out.extend_from_slice(&u16(entries.len() as u16)); // entries this disk
    out.extend_from_slice(&u16(entries.len() as u16)); // total entries
    out.extend_from_slice(&u32(cd_size));
    out.extend_from_slice(&u32(cd_offset));
    out.extend_from_slice(&u16(0)); // comment len
    out
}

/// Build a minimal, valid ZIP using only STORED entries.
fn build_zip(entries: &[Entry]) -> Vec<u8> {
    let raw: Vec<RawEntry> = entries
        .iter()
        .map(|e| RawEntry {
            name: e.name,
            stored: e.data,
            uncompressed_size: e.data.len() as u32,
            crc32: crc32fast::hash(e.data),
            method: 0,
        })
        .collect();
    build_zip_general(&raw)
}

/// Build a ZIP with explicit `(name, stored_bytes, uncompressed, method)`
/// entries (used to construct DEFLATE entries).
fn build_zip_methods(entries: &[(&str, &[u8], &[u8], u16)]) -> Vec<u8> {
    let raw: Vec<RawEntry> = entries
        .iter()
        .map(|(name, stored, uncompressed, method)| RawEntry {
            name,
            stored,
            uncompressed_size: uncompressed.len() as u32,
            crc32: crc32fast::hash(uncompressed),
            method: *method,
        })
        .collect();
    build_zip_general(&raw)
}

fn sample_dcp() -> Vec<u8> {
    build_zip(&[
        Entry {
            name: "COSCAP.BIN.xdelta",
            data: b"delta-bytes",
        },
        Entry {
            name: "data/R01.MLT.xdelta",
            data: b"nested-delta",
        },
        Entry {
            name: "R10CAP.BIN",
            data: b"verbatim-new-file",
        },
        Entry {
            name: "bootsector/IP.BIN",
            data: &[0u8; 16],
        },
        Entry {
            name: "emptydir/",
            data: b"",
        },
    ])
}

#[test]
fn reads_central_directory_entries() {
    let zip = sample_dcp();
    let entries = read_central_directory(&mut Cursor::new(zip)).expect("read cd");
    let names: Vec<_> = entries.iter().map(|e| e.name.as_str()).collect();
    assert_eq!(
        names,
        vec![
            "COSCAP.BIN.xdelta",
            "data/R01.MLT.xdelta",
            "R10CAP.BIN",
            "bootsector/IP.BIN",
            "emptydir/",
        ]
    );
    let coscap = &entries[0];
    assert_eq!(coscap.uncompressed_size, b"delta-bytes".len() as u32);
    assert_eq!(coscap.method, 0);
}

#[test]
fn classifies_entries_per_dcp_convention() {
    let zip = sample_dcp();
    let manifest = read_manifest(&mut Cursor::new(zip)).expect("manifest");

    assert_eq!(manifest.delta_count(), 2);
    assert_eq!(manifest.verbatim_count(), 1);
    assert!(manifest.has_boot_sector());
    // Directory marker is skipped.
    assert_eq!(manifest.operations.len(), 4);

    assert!(matches!(
        &manifest.operations[0],
        DcpOperation::Delta { target, .. } if target == "COSCAP.BIN"
    ));
    assert!(matches!(
        &manifest.operations[1],
        DcpOperation::Delta { target, .. } if target == "data/R01.MLT"
    ));
    assert!(matches!(
        &manifest.operations[2],
        DcpOperation::Verbatim { path, .. } if path == "R10CAP.BIN"
    ));
    assert!(matches!(
        &manifest.operations[3],
        DcpOperation::BootSector { .. }
    ));

    let mut sources = manifest.required_source_paths();
    sources.sort();
    assert_eq!(sources, vec!["COSCAP.BIN", "data/R01.MLT"]);
}

#[test]
fn manifest_without_boot_sector() {
    let zip = build_zip(&[
        Entry {
            name: "A.BIN.xdelta",
            data: b"d",
        },
        Entry {
            name: "NEW.DAT",
            data: b"x",
        },
    ]);
    let manifest = read_manifest(&mut Cursor::new(zip)).expect("manifest");
    assert!(!manifest.has_boot_sector());
    assert_eq!(manifest.delta_count(), 1);
    assert_eq!(manifest.verbatim_count(), 1);
}

#[test]
fn empty_manifest_is_default() {
    assert_eq!(DcpManifest::from_entries(&[]), DcpManifest::default());
}

// --- Apply pipeline ---------------------------------------------------------

const SECTOR: usize = 2048;

fn both_endian_u32(v: u32) -> [u8; 8] {
    let le = v.to_le_bytes();
    let be = v.to_be_bytes();
    [le[0], le[1], le[2], le[3], be[0], be[1], be[2], be[3]]
}

fn dir_record(lba: u32, len: u32, is_dir: bool, name: &[u8]) -> Vec<u8> {
    let mut rlen = 33 + name.len();
    if rlen % 2 == 1 {
        rlen += 1;
    }
    let mut r = vec![0u8; rlen];
    r[0] = rlen as u8;
    r[2..10].copy_from_slice(&both_endian_u32(lba));
    r[10..18].copy_from_slice(&both_endian_u32(len));
    r[25] = if is_dir { 0x02 } else { 0x00 };
    r[28..30].copy_from_slice(&1u16.to_le_bytes());
    r[30..32].copy_from_slice(&1u16.to_be_bytes());
    r[32] = name.len() as u8;
    r[33..33 + name.len()].copy_from_slice(name);
    r
}

/// Build a tiny flat (root-only) cooked ISO9660 image (bias 0) holding the
/// given files, then open it as a [`GdRomFs`].
fn flat_gdrom(files: &[(&str, &[u8])]) -> GdRomFs<Cursor<Vec<u8>>> {
    let root_sector = 18u32;
    let mut next = 19u32;
    let mut placed = Vec::new();
    for (name, data) in files {
        placed.push((*name, *data, next));
        next += (data.len().div_ceil(SECTOR)).max(1) as u32;
    }
    let total = next;
    let mut image = vec![0u8; total as usize * SECTOR];

    // PVD at sector 16.
    let off = 16 * SECTOR;
    image[off] = 1;
    image[off + 1..off + 6].copy_from_slice(b"CD001");
    image[off + 6] = 1;
    image[off + 80..off + 88].copy_from_slice(&both_endian_u32(total));
    image[off + 128..off + 130].copy_from_slice(&(SECTOR as u16).to_le_bytes());
    image[off + 130..off + 132].copy_from_slice(&(SECTOR as u16).to_be_bytes());
    let root_rec = dir_record(root_sector, SECTOR as u32, true, &[0x00]);
    image[off + 156..off + 156 + root_rec.len()].copy_from_slice(&root_rec);

    // Terminator at sector 17.
    let t = 17 * SECTOR;
    image[t] = 255;
    image[t + 1..t + 6].copy_from_slice(b"CD001");

    // Root directory at sector 18.
    let mut dir = Vec::new();
    dir.extend(dir_record(root_sector, SECTOR as u32, true, &[0x00]));
    dir.extend(dir_record(root_sector, SECTOR as u32, true, &[0x01]));
    for (name, data, lba) in &placed {
        dir.extend(dir_record(
            *lba,
            data.len() as u32,
            false,
            format!("{name};1").as_bytes(),
        ));
    }
    let rd = root_sector as usize * SECTOR;
    image[rd..rd + dir.len()].copy_from_slice(&dir);

    // File data.
    for (_, data, lba) in &placed {
        let p = *lba as usize * SECTOR;
        image[p..p + data.len()].copy_from_slice(data);
    }

    GdRomFs::open(Cursor::new(image), 0).expect("open synthetic gd-rom")
}

/// Build a STORED `.dcp` from owned (name, bytes) pairs.
fn build_dcp(entries: &[(&str, &[u8])]) -> Vec<u8> {
    let specs: Vec<Entry> = entries
        .iter()
        .map(|&(name, data)| Entry { name, data })
        .collect();
    build_zip(&specs)
}

#[test]
fn extract_entry_handles_stored_and_deflate() {
    // STORED entry.
    let stored = build_zip(&[Entry {
        name: "S.BIN",
        data: b"stored-bytes",
    }]);
    let entries = read_central_directory(&mut Cursor::new(stored.clone())).unwrap();
    assert_eq!(
        extract_entry(&mut Cursor::new(stored), &entries[0]).unwrap(),
        b"stored-bytes"
    );

    // DEFLATE entry: compress a payload and hand-assemble a one-entry zip.
    let payload = b"deflate me, deflate me, deflate me!".repeat(4);
    let compressed = miniz_oxide::deflate::compress_to_vec(&payload, 6);
    let zip = build_zip_methods(&[("D.BIN", compressed.as_slice(), payload.as_slice(), 8u16)]);
    let entries = read_central_directory(&mut Cursor::new(zip.clone())).unwrap();
    assert_eq!(entries[0].method, 8);
    assert_eq!(
        extract_entry(&mut Cursor::new(zip), &entries[0]).unwrap(),
        payload
    );
}

#[test]
fn apply_dcp_applies_delta_verbatim_and_boot_sector() {
    let mut fs = flat_gdrom(&[("TEST.BIN", HELLO_SOURCE), ("KEEP.DAT", b"untouched")]);
    let dcp = build_dcp(&[
        ("TEST.BIN.xdelta", HELLO_DELTA),
        ("NEW.DAT", b"a freshly added file"),
        ("bootsector/IP.BIN", IP_BIN_STUB),
    ]);

    let mut outputs = Vec::new();
    let summary = apply_dcp(&mut Cursor::new(dcp), &mut fs, |o| {
        outputs.push(o);
        Ok(())
    })
    .expect("apply");

    assert_eq!(summary.deltas_applied, 1);
    assert_eq!(summary.verbatim_written, 1);
    assert!(summary.boot_sector);

    assert_eq!(
        outputs[0],
        DcpOutput::File {
            path: "TEST.BIN".into(),
            bytes: HELLO_TARGET.to_vec()
        }
    );
    assert_eq!(
        outputs[1],
        DcpOutput::File {
            path: "NEW.DAT".into(),
            bytes: b"a freshly added file".to_vec()
        }
    );
    assert_eq!(
        outputs[2],
        DcpOutput::BootSector {
            bytes: IP_BIN_STUB.to_vec()
        }
    );
}

#[test]
fn rebuild_track_streams_patched_disc() {
    use super::rebuild::rebuild_track_to_writer;
    use crate::gdrom::IsoTimestamp;

    // Source disc: a zero-byte file that sorts first (so a streaming desync
    // would corrupt everything after it), a file the patch modifies, and one it
    // leaves alone.
    let mut source = flat_gdrom(&[
        ("AAA_EMPTY.DAT", b""),
        ("TEST.BIN", HELLO_SOURCE),
        ("KEEP.DAT", b"left untouched"),
    ]);
    // Patch: a delta on TEST.BIN + a new verbatim file.
    let dcp = build_dcp(&[
        ("TEST.BIN.xdelta", HELLO_DELTA),
        ("NEW.DAT", b"added by the patch"),
    ]);

    let mut track: Vec<u8> = Vec::new();
    let summary = rebuild_track_to_writer(
        &mut Cursor::new(dcp),
        &mut source,
        IsoTimestamp::default(),
        &mut track,
    )
    .expect("rebuild");
    assert_eq!(summary.file_count, 4); // AAA_EMPTY.DAT, TEST.BIN, KEEP.DAT, NEW.DAT
    assert!(!summary.boot_sector_replaced);

    // The rebuilt track is a raw MODE1/2352 image; re-read it and verify.
    let mut rebuilt = GdRomFs::open(Cursor::new(track), 0).expect("reopen rebuilt track");
    let names: Vec<_> = rebuilt.files().keys().cloned().collect();
    assert_eq!(
        names,
        vec!["AAA_EMPTY.DAT", "KEEP.DAT", "NEW.DAT", "TEST.BIN"]
    );
    let empty = rebuilt.file("AAA_EMPTY.DAT").expect("empty file").clone();
    assert_eq!(empty.size, 0);
    assert_eq!(rebuilt.read_file(&empty).unwrap(), Vec::<u8>::new());

    let test = rebuilt.file("TEST.BIN").expect("patched file").clone();
    assert_eq!(rebuilt.read_file(&test).unwrap(), HELLO_TARGET);
    let keep = rebuilt.file("KEEP.DAT").expect("kept file").clone();
    assert_eq!(rebuilt.read_file(&keep).unwrap(), b"left untouched");
    let new = rebuilt.file("NEW.DAT").expect("new file").clone();
    assert_eq!(rebuilt.read_file(&new).unwrap(), b"added by the patch");
}

#[test]
fn apply_dcp_errors_when_delta_source_missing() {
    let mut fs = flat_gdrom(&[("OTHER.BIN", b"not the target")]);
    let dcp = build_dcp(&[("TEST.BIN.xdelta", HELLO_DELTA)]);
    let err = match apply_dcp(&mut Cursor::new(dcp), &mut fs, |_| Ok(())) {
        Ok(_) => panic!("expected missing-source error"),
        Err(e) => e,
    };
    assert!(matches!(
        err,
        rom_weaver_core::RomWeaverError::Validation(_)
    ));
}
