import type { WorkflowProgressStage } from "../../types/progress.ts";

type LocaleCode = string;

type MessageId =
  | `candidate.${string}`
  | `error.${string}`
  | `output.${string}`
  | `progress.${WorkflowProgressStage}`
  | `settings.${string}`
  | `ui.${string}`;

type MessageCatalog = Record<MessageId, string>;
type PartialMessageCatalog = Partial<MessageCatalog>;

/* The ui.* namespace is the loom workbench chrome (ported from the design
   prototype, which shipped full en/es/de catalogs). Plural ids end in
   ".one"/".other" and are resolved via Localizer.messageCount. */
const ENGLISH_MESSAGES = {
  "candidate.ambiguous": "Choose which {role} to use from {sourceName}.",
  "candidate.file": "file",
  "candidate.group": "group {kind}",
  "candidate.rerun": "Rerun with {optionName} <id>.",
  "candidate.selectable": "Selectable {role} files:",
  "candidate.warningCount": "{count} warning(s)",
  "error.AMBIGUOUS_SELECTION": "Multiple matching files were found.",
  "error.CANCELLED": "Workflow was cancelled.",
  "error.CHECKSUM_MISMATCH": "Checksum validation failed.",
  "error.COMPRESSION_FAILED": "Compression failed.",
  "error.INVALID_INPUT": "The selected input is not valid.",
  "error.INVALID_SETTINGS": "The selected settings are not valid.",
  "error.NO_COMPATIBLE_PATCH": "No compatible patch was found.",
  "error.NO_SELECTABLE_CANDIDATE": "No selectable file was found.",
  "error.OUTPUT_WRITE_FAILED": "Output could not be written.",
  "error.PATCH_APPLY_FAILED": "Patch application failed.",
  "error.PATCH_CREATE_FAILED": "Patch creation failed.",
  "error.PATCH_PARSE_FAILED": "Patch parsing failed.",
  "error.PATCH_TARGET_MISMATCH": "The patch target did not match the selected input.",
  "error.SELECTION_NOT_FOUND": "The selected file was not found.",
  "error.SOURCE_NOT_FOUND": "The selected source could not be found.",
  "error.SOURCE_UNSUPPORTED": "The selected source type is not supported.",
  "error.STORAGE_UNAVAILABLE": "Storage is unavailable.",
  "error.UNSUPPORTED_FORMAT": "The selected file format is not supported.",
  "error.WORKER_FAILED": "Worker execution failed.",
  "error.WORKER_UNAVAILABLE": "Required worker support is unavailable.",
  "output.created": "Created {fileName}",
  "output.saved": "successfully saved to {path}",
  "output.sizeChange": "{percent} {direction}",
  "output.sizeRatio": "{percent} of raw",
  "progress.apply": "Applying patch",
  "progress.checksum": "Checking checksum",
  "progress.compress": "Compressing output",
  "progress.create": "Creating patch",
  "progress.decompress": "Decompressing input",
  "progress.detect": "Detecting files",
  "progress.parse": "Parsing patch",
  "progress.select": "Selecting file",
  "progress.trim": "Trimming ROM",
  "progress.verify": "Verifying output",
  "progress.write": "Writing output",
  "settings.chdCreateCdCodecs": "CD Codecs",
  "settings.chdCreateDvdCodecs": "DVD Codecs",
  "settings.compression": "Compression",
  "settings.compressionProfile": "Level",
  "settings.fixChecksum": "Fix ROM header",
  "settings.language": "Language",
  "settings.logLevel": "Log level",
  "settings.requireInputChecksumMatch": "Require input match",
  "settings.requireOutputChecksumMatch": "Require output match",
  "settings.rvzBlockSize": "RVZ block size",
  "settings.rvzCodec": "RVZ codec",
  "settings.rvzCompressionLevel": "Level override",
  "settings.sevenZipCodec": "7z codec",
  "settings.sevenZipLevel": "Level override",
  "settings.workerThreads": "Worker threads",
  "settings.z3dsCompressionLevel": "Level override",
  "settings.zipCodec": "ZIP codec",
  "settings.zipLevel": "Level override",
  "ui.announce.copied": "Copied to clipboard",
  "ui.announce.reordered": "Patch moved to position {n}",
  "ui.cks.label": "Checks",
  "ui.common.cancel": "Cancel",
  "ui.common.close": "Close",
  "ui.common.copy": "Copy",
  "ui.common.dismiss": "Dismiss",
  "ui.common.remove": "Remove",
  "ui.common.retry": "Retry",
  "ui.confirm.body": "This clears every staged ROM and patch from the workbench. Files on disk are not touched.",
  "ui.confirm.confirm": "Remove all",
  "ui.confirm.title": "Remove all inputs?",
  "ui.confirm.trimBody":
    "Trimming writes a new, smaller ROM — this is permanent. Your original file is left untouched and an untrimmed copy is kept, so you can restore it.",
  "ui.confirm.trimConfirm": "Trim ROM",
  "ui.confirm.trimTitle": "Trim ROM?",
  "ui.create.swap": "Swap",
  "ui.cue.label": "Cue",
  "ui.drawer.extract": "Extract",
  "ui.drawer.tracks": "Tracks & checks",
  "ui.drawer.verifications": "Verify",
  "ui.drop.add": "Replace the ROM or add patches",
  "ui.drop.addCreate": "Add or replace a ROM",
  "ui.drop.addPatches": "Drop patch files",
  "ui.drop.addTrim": "Replace the ROM",
  "ui.drop.anywhereShort": "click to browse — or drop files anywhere on the page",
  "ui.drop.cancelStage": "Cancel reading",
  "ui.drop.hero": "Drop a ROM or patches",
  "ui.drop.heroCreate": "Drop the original and modified ROMs",
  "ui.drop.heroTrim": "Drop a ROM to trim",
  "ui.drop.hint":
    "click or drop files anywhere on the page — archives, containers, cue sheets and softpatches resolve automatically",
  "ui.drop.modified": "Drop the modified ROM",
  "ui.drop.original": "Drop the original ROM",
  "ui.drop.release": "Release to stage files",
  "ui.drop.staging": "Reading dropped files…",
  "ui.drop.tap": "Tap to choose files",
  "ui.drop.tapAnywhere": "Tap anywhere to choose files",
  "ui.empty.needsInput": "Add your files in {loc} above to begin",
  "ui.empty.needsInputNoun": "Add {noun} in {loc} above",
  "ui.env.threads": "threads",
  "ui.fault.copy": "Copy report",
  "ui.fault.remedyK": "Remedy",
  "ui.footer.donate": "Donate",
  "ui.gdi.label": "GDI",
  "ui.info.aria": "More info",
  "ui.info.chdCd": "Valid: cdlz, cdzl, cdfl. Entries without a level use the Level profile.",
  "ui.info.chdDvd": "Valid: lzma, zlib, huff, flac. huff has no level.",
  "ui.info.compressType": "Optionally wrap the output in a compressed container — “none” writes the raw file.",
  "ui.info.createModified":
    "Your edited build — the file the patch should reproduce; only the differences from the original are encoded; the size may differ from the original (growth is supported).",
  "ui.info.createOriginal":
    "The clean, unmodified dump that players already own; its checksum is embedded in the patch as the apply requirement; archives and containers resolve automatically.",
  "ui.info.fixHeader": "Recalculates internal header checksums after patching so clean dumps verify again.",
  "ui.info.level":
    "Profile → level: Min 0/−7 · Medium 5/11 · Max 9/22 (standard / zstd). A codec:level entry in a codec list overrides this.",
  "ui.info.output":
    "Set the filename without an extension — the format select controls it. Containers (zip, 7z, chd, rvz) are written directly.",
  "ui.info.outputOptions":
    "Codec and level defaults come from Settings › Compression; changes here affect only this job.",
  "ui.info.patches":
    "Patches apply top to bottom — drag the handle to reorder. Filename hints (crc32 / size) are checked before the run.",
  "ui.info.romInput":
    "Archives are decompressed and the ROM is located automatically; chd/rvz/z3ds containers are unpacked before patching; nested archives resolve recursively. RetroArch softpatch naming is supported.",
  "ui.info.rvzBlock": "Default 128 KiB. Larger blocks compress better but seek slower.",
  "ui.info.rvzCodec": "Default zstd. Optional level: zstd:-7 through zstd:22.",
  "ui.info.sevenZipCodec": "7z output currently uses LZMA2.",
  "ui.info.threads": "“auto” resolves to the browser-reported core count of {n}.",
  "ui.info.trimPad": "Byte expected in the tail run; auto detects 0x00 or 0xFF.",
  "ui.info.trimRom":
    "Tail trim: nds, dsi, srl (0x00 padding) and gba, 3ds (0xFF) — the trailing run is detected and removed; Xbox xiso images (.xiso or .iso) trim their unused tail; GameCube/Wii images (iso, gcm, wbfs, rvz) trim by scrubbing junk blocks during RVZ conversion; the original file is untouched and an untrimmed copy is kept for restore.",
  "ui.info.units": "MB counts in decimal (10⁶ bytes), MiB in binary (2²⁰ bytes). Sizes everywhere follow this choice.",
  "ui.info.verification": "Block the run when input or output hashes don’t match the patch requirements.",
  "ui.info.window": "Diff window for create — larger spans find moved data but use more memory.",
  "ui.info.zipCodec": "Valid: deflate, zstd, store. zstd writes ZIP-compatible output; store ignores Level.",
  "ui.log.emptyFilter": "No lines match “{q}”",
  "ui.log.filter": "Filter",
  "ui.log.filterLabel": "Filter log",
  "ui.mode.apply": "Apply",
  "ui.mode.create": "Create",
  "ui.mode.trim": "Trim",
  "ui.needs.modified": "the modified ROM",
  "ui.needs.original": "the original ROM",
  "ui.needs.patches": "patches",
  "ui.needs.rom": "a ROM",
  "ui.needs.source": "a ROM",
  "ui.opt.autoTrim": "Auto-trim before hashing (→ {size})",
  "ui.opt.autoTrimShort": "auto-trim",
  "ui.opt.fixHeader": "Fix ROM header before diff (512 B copier header)",
  "ui.opt.fixHeaderShort": "header fix",
  "ui.opt.rebuildCue": "Rebuild cue sheet for the patched output",
  "ui.opt.rebuildCueShort": "rebuild cue",
  "ui.opt.rebuildGdi": "Rebuild .gdi index for the patched output",
  "ui.opt.rebuildGdiShort": "rebuild gdi",
  "ui.opt.sizeGrowth": "Allow size growth (truncation record)",
  "ui.opt.sizeGrowthShort": "size growth",
  "ui.opt.sourceWindow": "Source window",
  "ui.opt.sourceWindowShort": "window",
  "ui.opts.output": "Options",
  "ui.opts.patch": "Options",
  "ui.opts.rom": "Options",
  "ui.opts.title": "Options",
  "ui.opts.trimPad": "Padding byte",
  "ui.opts.trimVerify": "Verify output after trim",
  "ui.opts.window": "Diff window",
  "ui.out.placeholder": "Output filename (no extension)",
  "ui.patch.embed": "Embed source crc32 in the output filename",
  "ui.patch.format": "Format",
  "ui.patch.off.one": "{n} disabled",
  "ui.patch.off.other": "{n} disabled",
  "ui.patch.offCount.one": "{n} patch is off — tick it to include it",
  "ui.patch.offCount.other": "{n} patches are off — tick them to include them",
  "ui.patch.on": "On",
  "ui.patch.parsing": "Parsing {name}…",
  "ui.patch.reorder": "Drag to reorder — arrow keys move",
  "ui.patch.stateOff": "Off",
  "ui.patch.target": "Target",
  "ui.patch.toggle": "Include {name}",
  "ui.patch.undo": "Undo-aware re-apply (revalidates patched blocks)",
  "ui.picker.hint": "The archive contains more than one candidate — pick the ones to stage.",
  "ui.picker.skipped": "skipped",
  "ui.picker.use": "Use selection",
  "ui.progress.threads": "{n} threads",
  "ui.req.embeddedSizes": "embedded sizes",
  "ui.req.patchedCrc32": "patched crc32",
  "ui.req.present": "present",
  "ui.req.rebuiltCue": "rebuilt cue",
  "ui.req.rebuiltGdi": "rebuilt gdi",
  "ui.req.sizesInOut": "in {in} → out {out}",
  "ui.req.targetBlockcheck": "target blockcheck",
  "ui.req.undoData": "undo data",
  "ui.result.archive": "{t} archive",
  "ui.result.created": "Patch created & verified",
  "ui.result.done": "Patched & verified",
  "ui.result.download": "Download",
  "ui.result.patchType": "{t} patch",
  "ui.result.raw": "raw {t}",
  "ui.result.records": "{n} delta records",
  "ui.result.trimmed": "Trimmed & verified",
  "ui.roms.extracting": "Extracting {name}…",
  "ui.roms.files.one": "{n} file",
  "ui.roms.files.other": "{n} files",
  "ui.roms.track": "Track {n}",
  "ui.roms.tracks.one": "{n} track",
  "ui.roms.tracks.other": "{n} tracks",
  "ui.run.apply.one": "Weave {n} patch",
  "ui.run.apply.other": "Weave {n} patches",
  "ui.run.applyEmpty": "Weave patches",
  "ui.run.create": "Create patch",
  "ui.run.trim": "Trim ROM",
  "ui.running.cancel": "Cancel job",
  "ui.scale.high": "High",
  "ui.scale.low": "Low",
  "ui.scale.max": "Max",
  "ui.scale.medium": "Medium",
  "ui.scale.min": "Min",
  "ui.scale.veryHigh": "Very High",
  "ui.scale.veryLow": "Very Low",
  "ui.settings.chdCd": "CD",
  "ui.settings.chdDvd": "DVD",
  "ui.settings.codecs": "Codecs",
  "ui.settings.defaultCompression": "Default format",
  "ui.settings.fixes": "Fixes",
  "ui.settings.general": "General",
  "ui.settings.reset": "Reset",
  "ui.settings.rvz": "RVZ",
  "ui.settings.rvzBlockSize": "Block size",
  "ui.settings.rvzCodec": "RVZ",
  "ui.settings.save": "Save",
  "ui.settings.sevenZipCodec": "7z",
  "ui.settings.threadsHint": "“auto” resolves to the browser-reported core count of {n}.",
  "ui.settings.title": "Settings",
  "ui.settings.units": "Size units",
  "ui.settings.validation": "Worker threads must be “auto” or a number between 1 and 64.",
  "ui.settings.verification": "Verification",
  "ui.settings.zipCodec": "ZIP",
  "ui.stage.apply": "Apply",
  "ui.stage.checksum": "Checksum",
  "ui.stage.compress": "Compress",
  "ui.stage.detect": "Detect",
  "ui.stage.diff": "Diff",
  "ui.stage.encode": "Encode",
  "ui.stage.extract": "Extract",
  "ui.stage.scan": "Scan",
  "ui.stage.trim": "Trim",
  "ui.stage.verify": "Verify",
  "ui.stage.write": "Write",
  "ui.status.done": "done",
  "ui.status.doneMsg": "rom-weaver finished in {t}",
  "ui.status.failed": "failed",
  "ui.status.faultMsg": "{code} at stage {stage}",
  "ui.status.idle": "idle",
  "ui.status.ready": "ready",
  "ui.status.running": "running",
  "ui.status.staging": "staging",
  "ui.step.apply": "Apply",
  "ui.step.inputs": "Inputs",
  "ui.step.modified": "Modified",
  "ui.step.original": "Original",
  "ui.step.output": "Output",
  "ui.step.patch": "Patch",
  "ui.step.patches": "Patches",
  "ui.step.rom": "ROM",
  "ui.theme.toDark": "Switch to dark theme",
  "ui.theme.toLight": "Switch to light theme",
  "ui.tools.log": "Log",
  "ui.track.word": "Track",
  "ui.trim.detected": "Trailing padding detected",
  "ui.trim.savings": "{from} → {to} ({p} smaller)",
  "ui.update.dialogTitle": "Update",
  "ui.update.later": "Later",
  "ui.update.note": "Reloading swaps the cached app. Running jobs are finished first.",
  "ui.update.ready": "Update ready",
  "ui.update.reload": "Reload",
  "ui.update.reloadNow": "Reload now",
  "ui.update.whatsNew": "What’s new",
  "ui.variant.asDumped": "File — as dumped",
  "ui.variant.autoTrimmed": "Auto-trimmed",
  "ui.variant.noHeader": "Without copier header",
  "ui.variant.withHeader": "File — as dumped (with 512 B header)",
  "ui.verdict.mismatch": "Mismatch",
  "ui.verify.ckHint": "CRC32, MD5, or SHA-1",
  "ui.verify.dryRun": "Dry-run",
  "ui.verify.dryRunDesc": "Apply to a scratch copy and re-hash — no source bytes touched",
  "ui.verify.dryRunFail": "Failed — scratch output differs",
  "ui.verify.dryRunPass": "Passed — scratch output re-hash matches",
  "ui.verify.expIn": "Expected input checksum",
  "ui.verify.expOut": "Expected output checksum",
  "ui.verify.input": "Input",
  "ui.verify.output": "Output",
  "ui.wakelock.text": "Screen stays awake while a job is running.",
  "ui.warn.ipsNoChecksum": "IPS carries no embedded checksums — gated by the filename hint only.",
} as const satisfies MessageCatalog;

const SPANISH_MESSAGES = {
  "candidate.ambiguous": "Elige qué {role} usar de {sourceName}.",
  "candidate.file": "archivo",
  "candidate.group": "grupo {kind}",
  "candidate.rerun": "Vuelve a ejecutar con {optionName} <id>.",
  "candidate.selectable": "Archivos de {role} seleccionables:",
  "candidate.warningCount": "{count} aviso(s)",
  "error.AMBIGUOUS_SELECTION": "Se encontraron varios archivos coincidentes.",
  "error.CANCELLED": "El flujo de trabajo se canceló.",
  "error.CHECKSUM_MISMATCH": "La validación de la suma de comprobación falló.",
  "error.COMPRESSION_FAILED": "La compresión falló.",
  "error.INVALID_INPUT": "La entrada seleccionada no es válida.",
  "error.INVALID_SETTINGS": "Los ajustes seleccionados no son válidos.",
  "error.NO_COMPATIBLE_PATCH": "No se encontró un parche compatible.",
  "error.NO_SELECTABLE_CANDIDATE": "No se encontró ningún archivo seleccionable.",
  "error.OUTPUT_WRITE_FAILED": "No se pudo escribir la salida.",
  "error.PATCH_APPLY_FAILED": "La aplicación del parche falló.",
  "error.PATCH_CREATE_FAILED": "La creación del parche falló.",
  "error.PATCH_PARSE_FAILED": "El análisis del parche falló.",
  "error.PATCH_TARGET_MISMATCH": "El destino del parche no coincide con la entrada seleccionada.",
  "error.SELECTION_NOT_FOUND": "El archivo seleccionado no se encontró.",
  "error.SOURCE_NOT_FOUND": "La fuente seleccionada no se encontró.",
  "error.SOURCE_UNSUPPORTED": "El tipo de fuente seleccionado no es compatible.",
  "error.STORAGE_UNAVAILABLE": "El almacenamiento no está disponible.",
  "error.UNSUPPORTED_FORMAT": "El formato de archivo seleccionado no es compatible.",
  "error.WORKER_FAILED": "La ejecución del worker falló.",
  "error.WORKER_UNAVAILABLE": "El soporte de workers requerido no está disponible.",
  "output.created": "Se creó {fileName}",
  "output.saved": "guardado correctamente en {path}",
  "output.sizeChange": "{percent} {direction}",
  "output.sizeRatio": "{percent} del original",
  "progress.apply": "Aplicando parche",
  "progress.checksum": "Comprobando suma",
  "progress.compress": "Comprimiendo salida",
  "progress.create": "Creando parche",
  "progress.decompress": "Descomprimiendo entrada",
  "progress.detect": "Detectando archivos",
  "progress.parse": "Analizando parche",
  "progress.select": "Seleccionando archivo",
  "progress.trim": "Recortando ROM",
  "progress.verify": "Verificando salida",
  "progress.write": "Escribiendo salida",
  "settings.chdCreateCdCodecs": "Códecs CD",
  "settings.chdCreateDvdCodecs": "Códecs DVD",
  "settings.compression": "Compresión",
  "settings.compressionProfile": "Nivel",
  "settings.fixChecksum": "Corregir cabecera ROM",
  "settings.language": "Idioma",
  "settings.logLevel": "Nivel de registro",
  "settings.requireInputChecksumMatch": "Exigir coincidencia de entrada",
  "settings.requireOutputChecksumMatch": "Exigir coincidencia de salida",
  "settings.rvzBlockSize": "Tamaño de bloque RVZ",
  "settings.rvzCodec": "Códec RVZ",
  "settings.rvzCompressionLevel": "Nivel personalizado",
  "settings.sevenZipCodec": "Códec 7z",
  "settings.sevenZipLevel": "Nivel personalizado",
  "settings.workerThreads": "Hilos de trabajo",
  "settings.z3dsCompressionLevel": "Nivel personalizado",
  "settings.zipCodec": "Códec ZIP",
  "settings.zipLevel": "Nivel personalizado",
  "ui.announce.copied": "Copiado al portapapeles",
  "ui.announce.reordered": "Parche movido a la posición {n}",
  "ui.cks.label": "Sumas",
  "ui.common.cancel": "Cancelar",
  "ui.common.close": "Cerrar",
  "ui.common.copy": "Copiar",
  "ui.common.dismiss": "Descartar",
  "ui.common.remove": "Quitar",
  "ui.common.retry": "Reintentar",
  "ui.confirm.body":
    "Esto limpia todos los ROM y parches preparados del banco de trabajo. Los archivos en disco no se tocan.",
  "ui.confirm.confirm": "Quitar todo",
  "ui.confirm.title": "¿Quitar todas las entradas?",
  "ui.confirm.trimBody":
    "Recortar escribe un ROM nuevo y más pequeño — es permanente. Tu archivo original queda intacto y se conserva una copia sin recortar para restaurarlo.",
  "ui.confirm.trimConfirm": "Recortar ROM",
  "ui.confirm.trimTitle": "¿Recortar ROM?",
  "ui.create.swap": "Intercambiar",
  "ui.cue.label": "Hoja cue",
  "ui.drawer.extract": "Extraer",
  "ui.drawer.tracks": "Pistas y sumas",
  "ui.drawer.verifications": "Verificar",
  "ui.drop.add": "Reemplaza el ROM o añade parches",
  "ui.drop.addCreate": "Añadir o reemplazar un ROM",
  "ui.drop.addPatches": "Suelta archivos de parche",
  "ui.drop.addTrim": "Reemplazar el ROM",
  "ui.drop.anywhereShort": "haz clic para explorar — o suelta archivos en cualquier parte de la página",
  "ui.drop.cancelStage": "Cancelar lectura",
  "ui.drop.hero": "Suelta un ROM o parches",
  "ui.drop.heroCreate": "Suelta el ROM original y el modificado",
  "ui.drop.heroTrim": "Suelta un ROM para recortar",
  "ui.drop.hint":
    "haz clic o suelta archivos en cualquier parte de la página — archivos, contenedores, hojas cue y softpatches se resuelven solos",
  "ui.drop.modified": "Suelta el ROM modificado",
  "ui.drop.original": "Suelta el ROM original",
  "ui.drop.release": "Suelta para preparar los archivos",
  "ui.drop.staging": "Leyendo archivos soltados…",
  "ui.drop.tap": "Toca para elegir archivos",
  "ui.drop.tapAnywhere": "Toca en cualquier parte para elegir archivos",
  "ui.empty.needsInput": "Añade tus archivos en {loc} arriba para empezar",
  "ui.empty.needsInputNoun": "Añade {noun} en {loc} arriba",
  "ui.env.threads": "hilos",
  "ui.fault.copy": "Copiar informe",
  "ui.fault.remedyK": "Solución",
  "ui.footer.donate": "Donar",
  "ui.gdi.label": "Índice GDI",
  "ui.info.aria": "Más información",
  "ui.info.chdCd": "Válidos: cdlz, cdzl, cdfl. Las entradas sin nivel usan el perfil de Nivel.",
  "ui.info.chdDvd": "Válidos: lzma, zlib, huff, flac. huff no tiene nivel.",
  "ui.info.compressType":
    "Opcionalmente envuelve la salida en un contenedor comprimido — «none» escribe el archivo tal cual.",
  "ui.info.createModified":
    "Tu versión modificada — el archivo que el parche debe reproducir; solo se codifican las diferencias con el original; el tamaño puede diferir del original (se admite el crecimiento).",
  "ui.info.createOriginal":
    "El volcado limpio y sin modificar que ya tienen los jugadores; su suma se incrusta en el parche como requisito de aplicación; archivos y contenedores se resuelven solos.",
  "ui.info.fixHeader":
    "Recalcula las sumas de la cabecera tras parchear para que los volcados limpios verifiquen de nuevo.",
  "ui.info.level":
    "Perfil → nivel: Mín 0/−7 · Medio 5/11 · Máx 9/22 (estándar / zstd). Una entrada codec:nivel lo anula.",
  "ui.info.output":
    "Escribe el nombre sin extensión — el selector de formato la controla. Los contenedores (zip, 7z, chd, rvz) se escriben directamente.",
  "ui.info.outputOptions":
    "Los códecs y niveles por defecto vienen de Ajustes › Compresión; los cambios aquí solo afectan a este trabajo.",
  "ui.info.patches":
    "Los parches se aplican de arriba abajo — arrastra el asa para reordenar. Las pistas del nombre (crc32 / tamaño) se comprueban antes de ejecutar.",
  "ui.info.romInput":
    "Los archivos se descomprimen y el ROM se localiza solo; los contenedores chd/rvz/z3ds se desempaquetan antes de parchear; los archivos anidados se resuelven recursivamente. Se admite el softpatch de RetroArch.",
  "ui.info.rvzBlock": "Por defecto 128 KiB. Bloques mayores comprimen mejor pero buscan más lento.",
  "ui.info.rvzCodec": "Por defecto zstd. Nivel opcional: zstd:-7 a zstd:22.",
  "ui.info.sevenZipCodec": "La salida 7z usa actualmente LZMA2.",
  "ui.info.threads": "«auto» usa el número de núcleos que reporta el navegador: {n}.",
  "ui.info.trimPad": "Byte esperado en la cola; auto detecta 0x00 o 0xFF.",
  "ui.info.trimRom":
    "Recorte de cola: nds, dsi, srl (relleno 0x00) y gba, 3ds (0xFF) — la cola se detecta y se elimina; las imágenes Xbox xiso (.xiso o .iso) recortan su cola sin usar; las imágenes de GameCube/Wii (iso, gcm, wbfs, rvz) recortan limpiando bloques basura al convertir a RVZ; tu archivo original no se toca y se conserva una copia sin recortar para restaurar.",
  "ui.info.units":
    "MB cuenta en decimal (10⁶ bytes), MiB en binario (2²⁰ bytes). Todos los tamaños siguen esta elección.",
  "ui.info.verification":
    "Bloquea la ejecución si las sumas de entrada o salida no coinciden con los requisitos del parche.",
  "ui.info.window": "Ventana de diff al crear — más grande encuentra datos movidos pero usa más memoria.",
  "ui.info.zipCodec": "Válidos: deflate, zstd, store. zstd escribe salida compatible con ZIP; store ignora el Nivel.",
  "ui.log.emptyFilter": "Ninguna línea coincide con «{q}»",
  "ui.log.filter": "Filtrar",
  "ui.log.filterLabel": "Filtrar el registro",
  "ui.mode.apply": "Aplicar",
  "ui.mode.create": "Crear",
  "ui.mode.trim": "Recortar",
  "ui.needs.modified": "el ROM modificado",
  "ui.needs.original": "el ROM original",
  "ui.needs.patches": "parches",
  "ui.needs.rom": "un ROM",
  "ui.needs.source": "un ROM",
  "ui.opt.autoTrim": "Auto-recortar antes de hashear (→ {size})",
  "ui.opt.autoTrimShort": "auto-recorte",
  "ui.opt.fixHeader": "Corregir la cabecera ROM antes del diff (cabecera de copiador de 512 B)",
  "ui.opt.fixHeaderShort": "corregir cabecera",
  "ui.opt.rebuildCue": "Regenerar la hoja cue para la salida parcheada",
  "ui.opt.rebuildCueShort": "regenerar cue",
  "ui.opt.rebuildGdi": "Regenerar el índice .gdi para la salida parcheada",
  "ui.opt.rebuildGdiShort": "regenerar gdi",
  "ui.opt.sizeGrowth": "Permitir crecimiento de tamaño (registro de truncado)",
  "ui.opt.sizeGrowthShort": "crecimiento",
  "ui.opt.sourceWindow": "Ventana de origen",
  "ui.opt.sourceWindowShort": "ventana",
  "ui.opts.output": "Opciones",
  "ui.opts.patch": "Opciones",
  "ui.opts.rom": "Opciones",
  "ui.opts.title": "Opciones",
  "ui.opts.trimPad": "Byte de relleno",
  "ui.opts.trimVerify": "Verificar la salida tras recortar",
  "ui.opts.window": "Ventana de diff",
  "ui.out.placeholder": "Nombre de salida (sin extensión)",
  "ui.patch.embed": "Incluir el crc32 de origen en el nombre de salida",
  "ui.patch.format": "Formato",
  "ui.patch.off.one": "{n} desactivado",
  "ui.patch.off.other": "{n} desactivados",
  "ui.patch.offCount.one": "{n} parche está desactivado — márcalo para incluirlo",
  "ui.patch.offCount.other": "{n} parches están desactivados — márcalos para incluirlos",
  "ui.patch.on": "Sí",
  "ui.patch.parsing": "Analizando {name}…",
  "ui.patch.reorder": "Arrastra para reordenar — las flechas mueven",
  "ui.patch.stateOff": "No",
  "ui.patch.target": "Destino",
  "ui.patch.toggle": "Incluir {name}",
  "ui.patch.undo": "Reaplicación con deshacer (revalida los bloques parcheados)",
  "ui.picker.hint": "El archivo contiene más de un candidato — elige cuáles preparar.",
  "ui.picker.skipped": "omitido",
  "ui.picker.use": "Usar selección",
  "ui.progress.threads": "{n} hilos",
  "ui.req.embeddedSizes": "tamaños integrados",
  "ui.req.patchedCrc32": "crc32 parcheado",
  "ui.req.present": "presente",
  "ui.req.rebuiltCue": "cue regenerada",
  "ui.req.rebuiltGdi": "gdi regenerado",
  "ui.req.sizesInOut": "entrada {in} → salida {out}",
  "ui.req.targetBlockcheck": "blockcheck de destino",
  "ui.req.undoData": "datos de deshacer",
  "ui.result.archive": "archivo {t}",
  "ui.result.created": "Parche creado y verificado",
  "ui.result.done": "Parcheado y verificado",
  "ui.result.download": "Descargar",
  "ui.result.patchType": "parche {t}",
  "ui.result.raw": "{t} sin comprimir",
  "ui.result.records": "{n} registros delta",
  "ui.result.trimmed": "Recortado y verificado",
  "ui.roms.extracting": "Extrayendo {name}…",
  "ui.roms.files.one": "{n} archivo",
  "ui.roms.files.other": "{n} archivos",
  "ui.roms.track": "Pista {n}",
  "ui.roms.tracks.one": "{n} pista",
  "ui.roms.tracks.other": "{n} pistas",
  "ui.run.apply.one": "Tejer {n} parche",
  "ui.run.apply.other": "Tejer {n} parches",
  "ui.run.applyEmpty": "Tejer parches",
  "ui.run.create": "Crear parche",
  "ui.run.trim": "Recortar ROM",
  "ui.running.cancel": "Cancelar trabajo",
  "ui.scale.high": "Alto",
  "ui.scale.low": "Bajo",
  "ui.scale.max": "Máx",
  "ui.scale.medium": "Medio",
  "ui.scale.min": "Mín",
  "ui.scale.veryHigh": "Muy alto",
  "ui.scale.veryLow": "Muy bajo",
  "ui.settings.chdCd": "CD",
  "ui.settings.chdDvd": "DVD",
  "ui.settings.codecs": "Códecs",
  "ui.settings.defaultCompression": "Formato por defecto",
  "ui.settings.fixes": "Correcciones",
  "ui.settings.general": "General",
  "ui.settings.reset": "Restablecer",
  "ui.settings.rvz": "RVZ",
  "ui.settings.rvzBlockSize": "Tamaño de bloque",
  "ui.settings.rvzCodec": "RVZ",
  "ui.settings.save": "Guardar",
  "ui.settings.sevenZipCodec": "7z",
  "ui.settings.threadsHint": "«auto» usa el número de núcleos que reporta el navegador: {n}.",
  "ui.settings.title": "Ajustes",
  "ui.settings.units": "Unidades de tamaño",
  "ui.settings.validation": "Los hilos deben ser «auto» o un número entre 1 y 64.",
  "ui.settings.verification": "Verificación",
  "ui.settings.zipCodec": "ZIP",
  "ui.stage.apply": "Aplicar",
  "ui.stage.checksum": "Suma",
  "ui.stage.compress": "Comprimir",
  "ui.stage.detect": "Detectar",
  "ui.stage.diff": "Comparar",
  "ui.stage.encode": "Codificar",
  "ui.stage.extract": "Extraer",
  "ui.stage.scan": "Escanear",
  "ui.stage.trim": "Recortar",
  "ui.stage.verify": "Verificar",
  "ui.stage.write": "Escribir",
  "ui.status.done": "hecho",
  "ui.status.doneMsg": "rom-weaver terminó en {t}",
  "ui.status.failed": "fallido",
  "ui.status.faultMsg": "{code} en la etapa {stage}",
  "ui.status.idle": "inactivo",
  "ui.status.ready": "listo",
  "ui.status.running": "ejecutando",
  "ui.status.staging": "preparando",
  "ui.step.apply": "Aplicar",
  "ui.step.inputs": "Entradas",
  "ui.step.modified": "Modificado",
  "ui.step.original": "Original",
  "ui.step.output": "Salida",
  "ui.step.patch": "Parche",
  "ui.step.patches": "Parches",
  "ui.step.rom": "ROM",
  "ui.theme.toDark": "Cambiar a tema oscuro",
  "ui.theme.toLight": "Cambiar a tema claro",
  "ui.tools.log": "Registro",
  "ui.track.word": "Pista",
  "ui.trim.detected": "Relleno final detectado",
  "ui.trim.savings": "{from} → {to} ({p} más pequeño)",
  "ui.update.dialogTitle": "Actualización",
  "ui.update.later": "Más tarde",
  "ui.update.note": "Recargar reemplaza la app en caché. Los trabajos en curso terminan primero.",
  "ui.update.ready": "Actualización lista",
  "ui.update.reload": "Recargar",
  "ui.update.reloadNow": "Recargar ahora",
  "ui.update.whatsNew": "Novedades",
  "ui.variant.asDumped": "Archivo — tal como se volcó",
  "ui.variant.autoTrimmed": "Auto-recortado",
  "ui.variant.noHeader": "Sin cabecera de copiador",
  "ui.variant.withHeader": "Archivo — tal como se volcó (con cabecera de 512 B)",
  "ui.verdict.mismatch": "Discrepancia",
  "ui.verify.ckHint": "CRC32, MD5 o SHA-1",
  "ui.verify.dryRun": "Simulación",
  "ui.verify.dryRunDesc": "Aplica sobre una copia temporal y re-hashea — sin tocar los bytes de origen",
  "ui.verify.dryRunFail": "Fallo — la salida de la copia difiere",
  "ui.verify.dryRunPass": "Correcto — el re-hash de la copia coincide",
  "ui.verify.expIn": "Suma de entrada esperada",
  "ui.verify.expOut": "Suma de salida esperada",
  "ui.verify.input": "Entrada",
  "ui.verify.output": "Salida",
  "ui.wakelock.text": "La pantalla permanece activa mientras se ejecuta un trabajo.",
  "ui.warn.ipsNoChecksum": "IPS no incluye sumas de comprobación — solo se valida con la pista del nombre de archivo.",
} as const satisfies PartialMessageCatalog;

const GERMAN_MESSAGES = {
  "candidate.ambiguous": "Wähle, welche {role} aus {sourceName} verwendet wird.",
  "candidate.file": "Datei",
  "candidate.group": "Gruppe {kind}",
  "candidate.rerun": "Erneut ausführen mit {optionName} <id>.",
  "candidate.selectable": "Wählbare {role}-Dateien:",
  "candidate.warningCount": "{count} Warnung(en)",
  "error.AMBIGUOUS_SELECTION": "Mehrere passende Dateien wurden gefunden.",
  "error.CANCELLED": "Der Workflow wurde abgebrochen.",
  "error.CHECKSUM_MISMATCH": "Die Prüfsummen-Validierung ist fehlgeschlagen.",
  "error.COMPRESSION_FAILED": "Die Kompression ist fehlgeschlagen.",
  "error.INVALID_INPUT": "Die gewählte Eingabe ist ungültig.",
  "error.INVALID_SETTINGS": "Die gewählten Einstellungen sind ungültig.",
  "error.NO_COMPATIBLE_PATCH": "Kein kompatibler Patch gefunden.",
  "error.NO_SELECTABLE_CANDIDATE": "Keine wählbare Datei gefunden.",
  "error.OUTPUT_WRITE_FAILED": "Die Ausgabe konnte nicht geschrieben werden.",
  "error.PATCH_APPLY_FAILED": "Das Anwenden des Patches ist fehlgeschlagen.",
  "error.PATCH_CREATE_FAILED": "Das Erstellen des Patches ist fehlgeschlagen.",
  "error.PATCH_PARSE_FAILED": "Das Parsen des Patches ist fehlgeschlagen.",
  "error.PATCH_TARGET_MISMATCH": "Das Patch-Ziel passt nicht zur gewählten Eingabe.",
  "error.SELECTION_NOT_FOUND": "Die gewählte Datei wurde nicht gefunden.",
  "error.SOURCE_NOT_FOUND": "Die gewählte Quelle wurde nicht gefunden.",
  "error.SOURCE_UNSUPPORTED": "Der gewählte Quelltyp wird nicht unterstützt.",
  "error.STORAGE_UNAVAILABLE": "Speicher ist nicht verfügbar.",
  "error.UNSUPPORTED_FORMAT": "Das gewählte Dateiformat wird nicht unterstützt.",
  "error.WORKER_FAILED": "Die Worker-Ausführung ist fehlgeschlagen.",
  "error.WORKER_UNAVAILABLE": "Die erforderliche Worker-Unterstützung fehlt.",
  "output.created": "{fileName} erstellt",
  "output.saved": "erfolgreich gespeichert unter {path}",
  "output.sizeChange": "{percent} {direction}",
  "output.sizeRatio": "{percent} der Rohgröße",
  "progress.apply": "Patch wird angewendet",
  "progress.checksum": "Prüfsumme wird geprüft",
  "progress.compress": "Ausgabe wird komprimiert",
  "progress.create": "Patch wird erstellt",
  "progress.decompress": "Eingabe wird entpackt",
  "progress.detect": "Dateien werden erkannt",
  "progress.parse": "Patch wird geparst",
  "progress.select": "Datei wird gewählt",
  "progress.trim": "ROM wird getrimmt",
  "progress.verify": "Ausgabe wird verifiziert",
  "progress.write": "Ausgabe wird geschrieben",
  "settings.chdCreateCdCodecs": "CD-Codecs",
  "settings.chdCreateDvdCodecs": "DVD-Codecs",
  "settings.compression": "Kompression",
  "settings.compressionProfile": "Stufe",
  "settings.fixChecksum": "ROM-Header korrigieren",
  "settings.language": "Sprache",
  "settings.logLevel": "Protokollstufe",
  "settings.requireInputChecksumMatch": "Eingabe-Übereinstimmung erzwingen",
  "settings.requireOutputChecksumMatch": "Ausgabe-Übereinstimmung erzwingen",
  "settings.rvzBlockSize": "RVZ-Blockgröße",
  "settings.rvzCodec": "RVZ-Codec",
  "settings.rvzCompressionLevel": "Eigene Stufe",
  "settings.sevenZipCodec": "7z-Codec",
  "settings.sevenZipLevel": "Eigene Stufe",
  "settings.workerThreads": "Worker-Threads",
  "settings.z3dsCompressionLevel": "Eigene Stufe",
  "settings.zipCodec": "ZIP-Codec",
  "settings.zipLevel": "Eigene Stufe",
  "ui.announce.copied": "In die Zwischenablage kopiert",
  "ui.announce.reordered": "Patch an Position {n} verschoben",
  "ui.cks.label": "Prüfungen",
  "ui.common.cancel": "Abbrechen",
  "ui.common.close": "Schließen",
  "ui.common.copy": "Kopieren",
  "ui.common.dismiss": "Verwerfen",
  "ui.common.remove": "Entfernen",
  "ui.common.retry": "Erneut",
  "ui.confirm.body":
    "Entfernt alle eingelegten ROMs und Patches von der Werkbank. Dateien auf der Festplatte bleiben unberührt.",
  "ui.confirm.confirm": "Alle entfernen",
  "ui.confirm.title": "Alle Eingaben entfernen?",
  "ui.confirm.trimBody":
    "Trimmen schreibt ein neues, kleineres ROM — das ist dauerhaft. Deine Originaldatei bleibt unberührt und eine ungetrimmte Kopie wird aufbewahrt, sodass du sie wiederherstellen kannst.",
  "ui.confirm.trimConfirm": "ROM trimmen",
  "ui.confirm.trimTitle": "ROM trimmen?",
  "ui.create.swap": "Tauschen",
  "ui.cue.label": "Cue",
  "ui.drawer.extract": "Entpacken",
  "ui.drawer.tracks": "Tracks & Prüfungen",
  "ui.drawer.verifications": "Prüfen",
  "ui.drop.add": "ROM ersetzen oder Patches hinzufügen",
  "ui.drop.addCreate": "ROM hinzufügen oder ersetzen",
  "ui.drop.addPatches": "Patch-Dateien ablegen",
  "ui.drop.addTrim": "ROM ersetzen",
  "ui.drop.anywhereShort": "klicken zum Durchsuchen — oder Dateien irgendwo auf der Seite ablegen",
  "ui.drop.cancelStage": "Lesen abbrechen",
  "ui.drop.hero": "ROM oder Patches ablegen",
  "ui.drop.heroCreate": "Original- und modifiziertes ROM ablegen",
  "ui.drop.heroTrim": "ROM zum Trimmen ablegen",
  "ui.drop.hint":
    "klicken oder Dateien irgendwo auf der Seite ablegen — Archive, Container, Cue-Sheets und Softpatches werden automatisch aufgelöst",
  "ui.drop.modified": "Modifiziertes ROM ablegen",
  "ui.drop.original": "Original-ROM ablegen",
  "ui.drop.release": "Loslassen, um Dateien einzulegen",
  "ui.drop.staging": "Abgelegte Dateien werden gelesen…",
  "ui.drop.tap": "Tippen, um Dateien zu wählen",
  "ui.drop.tapAnywhere": "Irgendwo tippen, um Dateien zu wählen",
  "ui.empty.needsInput": "Dateien in {loc} oben hinzufügen, um zu starten",
  "ui.empty.needsInputNoun": "{noun} in {loc} oben hinzufügen",
  "ui.env.threads": "Threads",
  "ui.fault.copy": "Bericht kopieren",
  "ui.fault.remedyK": "Abhilfe",
  "ui.footer.donate": "Spenden",
  "ui.gdi.label": "GDI",
  "ui.info.aria": "Mehr Infos",
  "ui.info.chdCd": "Gültig: cdlz, cdzl, cdfl. Einträge ohne Stufe nutzen das Stufen-Profil.",
  "ui.info.chdDvd": "Gültig: lzma, zlib, huff, flac. huff hat keine Stufe.",
  "ui.info.compressType":
    "Verpackt die Ausgabe optional in einen komprimierten Container — „none“ schreibt die Datei direkt.",
  "ui.info.createModified":
    "Dein bearbeiteter Build — die Datei, die der Patch erzeugen soll; nur die Unterschiede zum Original werden kodiert; die Größe darf vom Original abweichen (Wachstum wird unterstützt).",
  "ui.info.createOriginal":
    "Der saubere, unveränderte Dump, den Spieler bereits besitzen; seine Prüfsumme wird als Anwendungsvoraussetzung in den Patch eingebettet; Archive und Container werden automatisch aufgelöst.",
  "ui.info.fixHeader": "Berechnet Header-Prüfsummen nach dem Patchen neu, damit saubere Dumps wieder verifizieren.",
  "ui.info.level":
    "Profil → Stufe: Min 0/−7 · Mittel 5/11 · Max 9/22 (Standard / zstd). Ein codec:stufe-Eintrag überschreibt dies.",
  "ui.info.output":
    "Dateiname ohne Endung — das Format-Select steuert sie. Container (zip, 7z, chd, rvz) werden direkt geschrieben.",
  "ui.info.outputOptions":
    "Codec- und Stufen-Defaults kommen aus Einstellungen › Kompression; Änderungen hier gelten nur für diesen Job.",
  "ui.info.patches":
    "Patches werden von oben nach unten angewendet — zum Umsortieren am Griff ziehen. Dateinamen-Hinweise (crc32 / Größe) werden vor dem Lauf geprüft.",
  "ui.info.romInput":
    "Archive werden entpackt und das ROM automatisch gefunden; chd/rvz/z3ds-Container werden vor dem Patchen ausgepackt; verschachtelte Archive rekursiv aufgelöst. RetroArch-Softpatch-Namen werden unterstützt.",
  "ui.info.rvzBlock": "Standard 128 KiB. Größere Blöcke komprimieren besser, suchen aber langsamer.",
  "ui.info.rvzCodec": "Standard zstd. Optionale Stufe: zstd:-7 bis zstd:22.",
  "ui.info.sevenZipCodec": "7z-Ausgabe nutzt derzeit LZMA2.",
  "ui.info.threads": "„auto“ nutzt die vom Browser gemeldete Kernanzahl: {n}.",
  "ui.info.trimPad": "Erwartetes Byte im Schwanz; auto erkennt 0x00 oder 0xFF.",
  "ui.info.trimRom":
    "Tail-Trim: nds, dsi, srl (0x00-Padding) und gba, 3ds (0xFF) — der Füllbereich am Ende wird erkannt und entfernt; Xbox-xiso-Images (.xiso oder .iso) trimmen ihren ungenutzten Schwanz; GameCube/Wii-Images (iso, gcm, wbfs, rvz) trimmen durch Entfernen von Junk-Blöcken bei der RVZ-Konvertierung; die Originaldatei bleibt unberührt, eine ungetrimmte Kopie wird zum Wiederherstellen aufbewahrt.",
  "ui.info.units": "MB zählt dezimal (10⁶ Bytes), MiB binär (2²⁰ Bytes). Alle Größen folgen dieser Wahl.",
  "ui.info.verification": "Blockiert den Lauf, wenn Ein- oder Ausgabe-Hashes nicht zu den Patch-Anforderungen passen.",
  "ui.info.window": "Diff-Fenster beim Erstellen — größer findet verschobene Daten, braucht mehr Speicher.",
  "ui.info.zipCodec": "Gültig: deflate, zstd, store. zstd schreibt ZIP-kompatible Ausgabe; store ignoriert die Stufe.",
  "ui.log.emptyFilter": "Keine Zeile passt zu „{q}“",
  "ui.log.filter": "Filtern",
  "ui.log.filterLabel": "Protokoll filtern",
  "ui.mode.apply": "Anwenden",
  "ui.mode.create": "Erstellen",
  "ui.mode.trim": "Trimmen",
  "ui.needs.modified": "das modifizierte ROM",
  "ui.needs.original": "das Original-ROM",
  "ui.needs.patches": "Patches",
  "ui.needs.rom": "ein ROM",
  "ui.needs.source": "ein ROM",
  "ui.opt.autoTrim": "Vor dem Hashing auto-trimmen (→ {size})",
  "ui.opt.autoTrimShort": "Auto-Trim",
  "ui.opt.fixHeader": "ROM-Header vor dem Diff korrigieren (512-B-Copier-Header)",
  "ui.opt.fixHeaderShort": "Header-Fix",
  "ui.opt.rebuildCue": "Cue-Sheet für die gepatchte Ausgabe neu erzeugen",
  "ui.opt.rebuildCueShort": "Cue neu",
  "ui.opt.rebuildGdi": ".gdi-Index für die gepatchte Ausgabe neu erzeugen",
  "ui.opt.rebuildGdiShort": "GDI neu",
  "ui.opt.sizeGrowth": "Größenwachstum erlauben (Truncation-Record)",
  "ui.opt.sizeGrowthShort": "Wachstum",
  "ui.opt.sourceWindow": "Quellfenster",
  "ui.opt.sourceWindowShort": "Fenster",
  "ui.opts.output": "Optionen",
  "ui.opts.patch": "Optionen",
  "ui.opts.rom": "Optionen",
  "ui.opts.title": "Optionen",
  "ui.opts.trimPad": "Füllbyte",
  "ui.opts.trimVerify": "Ausgabe nach dem Trimmen verifizieren",
  "ui.opts.window": "Diff-Fenster",
  "ui.out.placeholder": "Ausgabedateiname (ohne Endung)",
  "ui.patch.embed": "Quell-crc32 in den Ausgabedateinamen einbetten",
  "ui.patch.format": "Format",
  "ui.patch.off.one": "{n} deaktiviert",
  "ui.patch.off.other": "{n} deaktiviert",
  "ui.patch.offCount.one": "{n} Patch ist aus — ankreuzen zum Einschließen",
  "ui.patch.offCount.other": "{n} Patches sind aus — ankreuzen zum Einschließen",
  "ui.patch.on": "An",
  "ui.patch.parsing": "Analysiere {name}…",
  "ui.patch.reorder": "Zum Umsortieren ziehen — Pfeiltasten verschieben",
  "ui.patch.stateOff": "Aus",
  "ui.patch.target": "Ziel",
  "ui.patch.toggle": "{name} einschließen",
  "ui.patch.undo": "Undo-fähiges Wiederanwenden (prüft gepatchte Blöcke erneut)",
  "ui.picker.hint": "Das Archiv enthält mehrere Kandidaten — wähle die einzulegenden Dateien.",
  "ui.picker.skipped": "übersprungen",
  "ui.picker.use": "Auswahl verwenden",
  "ui.progress.threads": "{n} Threads",
  "ui.req.embeddedSizes": "eingebettete Größen",
  "ui.req.patchedCrc32": "gepatchter crc32",
  "ui.req.present": "vorhanden",
  "ui.req.rebuiltCue": "neu erzeugtes Cue",
  "ui.req.rebuiltGdi": "neu erzeugtes GDI",
  "ui.req.sizesInOut": "ein {in} → aus {out}",
  "ui.req.targetBlockcheck": "Ziel-Blockcheck",
  "ui.req.undoData": "Undo-Daten",
  "ui.result.archive": "{t}-Archiv",
  "ui.result.created": "Patch erstellt & verifiziert",
  "ui.result.done": "Gepatcht & verifiziert",
  "ui.result.download": "Herunterladen",
  "ui.result.patchType": "{t}-Patch",
  "ui.result.raw": "{t} roh",
  "ui.result.records": "{n} Delta-Einträge",
  "ui.result.trimmed": "Getrimmt & verifiziert",
  "ui.roms.extracting": "Entpacke {name}…",
  "ui.roms.files.one": "{n} Datei",
  "ui.roms.files.other": "{n} Dateien",
  "ui.roms.track": "Track {n}",
  "ui.roms.tracks.one": "{n} Track",
  "ui.roms.tracks.other": "{n} Tracks",
  "ui.run.apply.one": "{n} Patch verweben",
  "ui.run.apply.other": "{n} Patches verweben",
  "ui.run.applyEmpty": "Patches verweben",
  "ui.run.create": "Patch erstellen",
  "ui.run.trim": "ROM trimmen",
  "ui.running.cancel": "Job abbrechen",
  "ui.scale.high": "Hoch",
  "ui.scale.low": "Niedrig",
  "ui.scale.max": "Max",
  "ui.scale.medium": "Mittel",
  "ui.scale.min": "Min",
  "ui.scale.veryHigh": "Sehr hoch",
  "ui.scale.veryLow": "Sehr niedrig",
  "ui.settings.chdCd": "CD",
  "ui.settings.chdDvd": "DVD",
  "ui.settings.codecs": "Codecs",
  "ui.settings.defaultCompression": "Standardformat",
  "ui.settings.fixes": "Korrekturen",
  "ui.settings.general": "Allgemein",
  "ui.settings.reset": "Zurücksetzen",
  "ui.settings.rvz": "RVZ",
  "ui.settings.rvzBlockSize": "Blockgröße",
  "ui.settings.rvzCodec": "RVZ",
  "ui.settings.save": "Speichern",
  "ui.settings.sevenZipCodec": "7z",
  "ui.settings.threadsHint": "„auto“ nutzt die vom Browser gemeldete Kernanzahl: {n}.",
  "ui.settings.title": "Einstellungen",
  "ui.settings.units": "Größeneinheiten",
  "ui.settings.validation": "Worker-Threads muss „auto“ oder eine Zahl zwischen 1 und 64 sein.",
  "ui.settings.verification": "Verifizierung",
  "ui.settings.zipCodec": "ZIP",
  "ui.stage.apply": "Anwenden",
  "ui.stage.checksum": "Prüfsumme",
  "ui.stage.compress": "Komprimieren",
  "ui.stage.detect": "Erkennen",
  "ui.stage.diff": "Vergleichen",
  "ui.stage.encode": "Kodieren",
  "ui.stage.extract": "Entpacken",
  "ui.stage.scan": "Scannen",
  "ui.stage.trim": "Trimmen",
  "ui.stage.verify": "Verifizieren",
  "ui.stage.write": "Schreiben",
  "ui.status.done": "fertig",
  "ui.status.doneMsg": "rom-weaver fertig in {t}",
  "ui.status.failed": "fehlgeschlagen",
  "ui.status.faultMsg": "{code} in Phase {stage}",
  "ui.status.idle": "inaktiv",
  "ui.status.ready": "bereit",
  "ui.status.running": "läuft",
  "ui.status.staging": "lädt",
  "ui.step.apply": "Anwenden",
  "ui.step.inputs": "Eingaben",
  "ui.step.modified": "Modifiziert",
  "ui.step.original": "Original",
  "ui.step.output": "Ausgabe",
  "ui.step.patch": "Patch",
  "ui.step.patches": "Patches",
  "ui.step.rom": "ROM",
  "ui.theme.toDark": "Zum dunklen Design wechseln",
  "ui.theme.toLight": "Zum hellen Design wechseln",
  "ui.tools.log": "Protokoll",
  "ui.track.word": "Track",
  "ui.trim.detected": "Padding am Ende erkannt",
  "ui.trim.savings": "{from} → {to} ({p} kleiner)",
  "ui.update.dialogTitle": "Update",
  "ui.update.later": "Später",
  "ui.update.note": "Neuladen tauscht die zwischengespeicherte App aus. Laufende Jobs werden zuerst beendet.",
  "ui.update.ready": "Update bereit",
  "ui.update.reload": "Neu laden",
  "ui.update.reloadNow": "Jetzt neu laden",
  "ui.update.whatsNew": "Neuigkeiten",
  "ui.variant.asDumped": "Datei — wie gedumpt",
  "ui.variant.autoTrimmed": "Automatisch getrimmt",
  "ui.variant.noHeader": "Ohne Copier-Header",
  "ui.variant.withHeader": "Datei — wie gedumpt (mit 512-B-Header)",
  "ui.verdict.mismatch": "Abweichung",
  "ui.verify.ckHint": "CRC32, MD5 oder SHA-1",
  "ui.verify.dryRun": "Probelauf",
  "ui.verify.dryRunDesc": "Auf eine Kopie anwenden und neu hashen — Quellbytes bleiben unberührt",
  "ui.verify.dryRunFail": "Fehlgeschlagen — Scratch-Ausgabe weicht ab",
  "ui.verify.dryRunPass": "Bestanden — Scratch-Ausgabe stimmt überein",
  "ui.verify.expIn": "Erwartete Eingangsprüfsumme",
  "ui.verify.expOut": "Erwartete Ausgangsprüfsumme",
  "ui.verify.input": "Eingang",
  "ui.verify.output": "Ausgang",
  "ui.wakelock.text": "Der Bildschirm bleibt aktiv, solange ein Job läuft.",
  "ui.warn.ipsNoChecksum": "IPS enthält keine eingebetteten Prüfsummen — nur durch den Dateinamen-Hinweis abgesichert.",
} as const satisfies PartialMessageCatalog;

const MESSAGE_CATALOGS: Record<LocaleCode, PartialMessageCatalog> = {
  de: GERMAN_MESSAGES,
  en: ENGLISH_MESSAGES,
  es: SPANISH_MESSAGES,
};

const DEFAULT_LOCALE = "en";

export type { LocaleCode, MessageCatalog, MessageId, PartialMessageCatalog };
export { DEFAULT_LOCALE, ENGLISH_MESSAGES, MESSAGE_CATALOGS };
