use std::{env, fs, path::Path};

use rom_weaver_app::{
    BundleChecks, BundleCommands, BundleCreateCommand, BundleCreateResult, BundleOutput,
    BundleParseCommand, BundleParseResult, BundlePatchEntry, BundlePatchSource, BundleRom,
    BundleSourceKind, BundleSourceRef, ChecksumCommand, Commands, CompressCommand,
    CompressionLevelProfile, ExtractCommand, ExtractStepDetails, ExtractedFileEntry, FilterKind,
    IngestCommand, IngestKind, IngestResult, IngestRomAsset, LogLevel, N64ByteOrder,
    OutputEnforceableEntry, PatchApplyCommand, PatchApplyHeaderMode, PatchApplyOutputHeaderMode,
    PatchBasisMode, PatchBasisSource, PatchCommands, PatchCreateCommand, PatchDescriptor,
    PatchInputBasis, PatchInputMatch, PatchInputVerdict, PatchN64ByteOrderMode, PatchPlanVerdict,
    PatchValidateCommand, PatchValidationPlan, PlanExtractBatchCommand, PpfUndoCommand,
    ProbeCommand, RomWeaverBundle, RomWeaverRunOutputOptions, RomWeaverRunRequest, ToolsCommands,
    TrimCommand, compression_metadata, patch_create_format_policy_metadata,
};
use rom_weaver_containers::{
    ArchiveExtensionAlias, ArchiveFormatMetadata, ContainerDefaultOutputMetadata,
    ContainerFormatMetadata, ContainerOutputExtensionStrategy, ContainerThreadCapabilityMetadata,
    archive_format_metadata, container_format_metadata, disc_image_policy_metadata,
    z3ds_subtype_metadata,
};
use rom_weaver_core::{
    CONTAINER_FILTER_FILE_EXTENSIONS, OperationFamily, OperationStatus,
    PATCH_FILTER_FILE_EXTENSIONS, ProgressEvent, ROM_FILTER_FILE_EXTENSIONS, RomWeaverErrorKind,
    ThreadBudget, ThreadExecution, ThreadMode,
};
use rom_weaver_patches::PatchRegistry;
use serde_json::{Map, Value, json};
use ts_rs::TS;

const TYPES_OUTPUT_PATH: &str =
    "packages/rom-weaver-webapp/src/wasm/generated/rom-weaver-rust-types.d.ts";
const METADATA_OUTPUT_PATH: &str =
    "packages/rom-weaver-webapp/src/wasm/generated/rom-weaver-format-metadata.ts";
const COMMAND_TYPES_OUTPUT_PATH: &str =
    "packages/rom-weaver-webapp/src/wasm/generated/rom-weaver-command-types.ts";
const TYPES_HEADER: &str = "// Generated by `mise run typegen`.\n// Do not edit manually.\n\n";
const METADATA_HEADER: &str = "// Generated by `mise run typegen`.\n// Do not edit manually.\n\n";
const COMMAND_TYPES_HEADER: &str =
    "// Generated by `mise run typegen`.\n// Do not edit manually.\n\n";
const RUNTIME_ALIAS_DECLS: &[&str] = &[
    "export type RomWeaverCommand = Commands;",
    "export type RomWeaverProgressEvent = ProgressEvent;",
    "export type RomWeaverRunJsonEvent = RomWeaverProgressEvent;",
    "export type RomWeaverRunInput = RomWeaverCommand | RomWeaverRunRequest;",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Mode {
    Write,
    Check,
}

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let mode = parse_mode(env::args().skip(1).collect())?;
    let outputs = [
        GeneratedOutput {
            path: TYPES_OUTPUT_PATH,
            rendered: strip_trailing_whitespace(render_types()),
        },
        GeneratedOutput {
            path: METADATA_OUTPUT_PATH,
            rendered: strip_trailing_whitespace(render_metadata()),
        },
        GeneratedOutput {
            path: COMMAND_TYPES_OUTPUT_PATH,
            rendered: strip_trailing_whitespace(render_command_types()),
        },
    ];

    match mode {
        Mode::Write => {
            for output in &outputs {
                write_output(output)?;
            }
            Ok(())
        }
        Mode::Check => {
            let mut stale_paths = Vec::new();
            for output in &outputs {
                if check_output(output)? {
                    println!("{} is up to date", output.path);
                } else {
                    stale_paths.push(output.path);
                }
            }
            if stale_paths.is_empty() {
                Ok(())
            } else {
                Err(format!(
                    "generated output is stale in {}; run `mise run typegen`",
                    stale_paths.join(", ")
                ))
            }
        }
    }
}

struct GeneratedOutput {
    path: &'static str,
    rendered: String,
}

fn write_output(output: &GeneratedOutput) -> Result<(), String> {
    let output_path = Path::new(output.path);
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }
    fs::write(output_path, &output.rendered)
        .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    println!("wrote {}", output_path.display());
    Ok(())
}

fn check_output(output: &GeneratedOutput) -> Result<bool, String> {
    let output_path = Path::new(output.path);
    let existing = fs::read_to_string(output_path).map_err(|error| {
        format!(
            "failed to read {} for --check (run with --write first): {error}",
            output_path.display()
        )
    })?;
    Ok(existing == output.rendered)
}

fn parse_mode(args: Vec<String>) -> Result<Mode, String> {
    match args.as_slice() {
        [flag] if flag == "--write" => Ok(Mode::Write),
        [flag] if flag == "--check" => Ok(Mode::Check),
        _ => Err("usage: rom-weaver-typegen --write | --check".to_string()),
    }
}

/// ts-rs renders multi-line struct declarations (structs whose fields carry doc
/// comments) with a trailing space on each line. Strip per-line trailing
/// whitespace from every generated file so they satisfy the repo's
/// `git diff --check` rule. Applied to both `--write` and `--check`, so the
/// output stays byte-stable between them.
fn strip_trailing_whitespace(rendered: String) -> String {
    let mut out = String::with_capacity(rendered.len());
    for segment in rendered.split_inclusive('\n') {
        match segment.strip_suffix('\n') {
            Some(line) => {
                out.push_str(line.trim_end());
                out.push('\n');
            }
            None => out.push_str(segment.trim_end()),
        }
    }
    out
}

fn render_types() -> String {
    let config = ts_rs::Config::default();
    let mut declarations = vec![
        export_decl::<OperationFamily>(&config),
        export_decl::<OperationStatus>(&config),
        export_decl::<RomWeaverErrorKind>(&config),
        export_decl::<ThreadMode>(&config),
        export_decl::<ThreadBudget>(&config),
        export_decl::<ThreadExecution>(&config),
        export_decl::<serde_json::Value>(&config),
        export_decl::<ProgressEvent>(&config),
        export_decl::<ExtractedFileEntry>(&config),
        export_decl::<ExtractStepDetails>(&config),
        export_decl::<IngestKind>(&config),
        export_decl::<IngestRomAsset>(&config),
        export_decl::<PatchDescriptor>(&config),
        export_decl::<IngestResult>(&config),
        export_decl::<CompressionLevelProfile>(&config),
        export_decl::<N64ByteOrder>(&config),
        export_decl::<PatchN64ByteOrderMode>(&config),
        export_decl::<PatchApplyHeaderMode>(&config),
        export_decl::<PatchApplyOutputHeaderMode>(&config),
        export_decl::<FilterKind>(&config),
        export_decl::<LogLevel>(&config),
        export_decl::<PatchInputBasis>(&config),
        export_decl::<PatchBasisMode>(&config),
        export_decl::<PatchBasisSource>(&config),
        export_decl::<PatchInputMatch>(&config),
        export_decl::<PatchInputVerdict>(&config),
        export_decl::<PatchPlanVerdict>(&config),
        export_decl::<OutputEnforceableEntry>(&config),
        export_decl::<PatchValidationPlan>(&config),
        export_decl::<ProbeCommand>(&config),
        export_decl::<ExtractCommand>(&config),
        export_decl::<ChecksumCommand>(&config),
        export_decl::<IngestCommand>(&config),
        export_decl::<CompressCommand>(&config),
        export_decl::<TrimCommand>(&config),
        export_decl::<PatchApplyCommand>(&config),
        export_decl::<PatchValidateCommand>(&config),
        export_decl::<PatchCreateCommand>(&config),
        export_decl::<PatchCommands>(&config),
        export_decl::<PpfUndoCommand>(&config),
        export_decl::<ToolsCommands>(&config),
        export_decl::<BundleChecks>(&config),
        export_decl::<BundleRom>(&config),
        export_decl::<BundlePatchEntry>(&config),
        export_decl::<BundleOutput>(&config),
        export_decl::<RomWeaverBundle>(&config),
        export_decl::<BundleSourceKind>(&config),
        export_decl::<BundleSourceRef>(&config),
        export_decl::<BundlePatchSource>(&config),
        export_decl::<BundleParseResult>(&config),
        export_decl::<BundleParseCommand>(&config),
        export_decl::<BundleCreateCommand>(&config),
        export_decl::<BundleCreateResult>(&config),
        export_decl::<BundleCommands>(&config),
        export_decl::<PlanExtractBatchCommand>(&config),
        export_decl::<Commands>(&config),
        export_decl::<RomWeaverRunOutputOptions>(&config),
        export_decl::<RomWeaverRunRequest>(&config),
    ];
    declarations.extend(RUNTIME_ALIAS_DECLS.iter().map(|decl| (*decl).to_string()));

    format!("{TYPES_HEADER}{}\n", declarations.join("\n\n"))
}

fn export_decl<T: TS>(config: &ts_rs::Config) -> String {
    let decl = T::decl(config);
    if decl.trim_start().starts_with("export ") {
        decl
    } else {
        format!("export {decl}")
    }
}

fn render_metadata() -> String {
    format!(
        "{METADATA_HEADER}{}\n\n{}\n\n{}\n\n{}\n\n{}\n\n{}\n\n{}\n\n{}\n\n{}\n\n{}\n\n{}\n",
        render_ts_const(
            "ROM_WEAVER_CREATE_PATCH_FORMAT_POLICY",
            create_patch_format_policy_value()
        ),
        render_ts_const("ROM_WEAVER_PATCH_FORMATS", patch_formats_value()),
        render_ts_const(
            "ROM_WEAVER_COMPRESSION_METADATA",
            compression_metadata_value()
        ),
        render_ts_const("ROM_WEAVER_FILE_FILTERS", file_filters_value()),
        render_ts_const("ROM_WEAVER_CONTAINER_FORMATS", container_formats_value()),
        render_ts_const(
            "ROM_WEAVER_CONTAINER_FORMAT_ALIASES",
            container_format_aliases_value()
        ),
        render_ts_const(
            "ROM_WEAVER_CREATE_CONTAINER_FORMATS",
            create_container_formats_value()
        ),
        render_ts_const("ROM_WEAVER_DISC_IMAGE_POLICY", disc_image_policy_value()),
        render_ts_const("ROM_WEAVER_ARCHIVE_FORMATS", archive_formats_value()),
        render_ts_const("ROM_WEAVER_Z3DS_SUBTYPES", z3ds_subtypes_value()),
        "export const ROM_WEAVER_FORMAT_METADATA = {\n  archiveFormats: ROM_WEAVER_ARCHIVE_FORMATS,\n  compression: ROM_WEAVER_COMPRESSION_METADATA,\n  containerFormatAliases: ROM_WEAVER_CONTAINER_FORMAT_ALIASES,\n  containerFormats: ROM_WEAVER_CONTAINER_FORMATS,\n  createContainerFormats: ROM_WEAVER_CREATE_CONTAINER_FORMATS,\n  createPatchFormatPolicy: ROM_WEAVER_CREATE_PATCH_FORMAT_POLICY,\n  discImagePolicy: ROM_WEAVER_DISC_IMAGE_POLICY,\n  fileFilters: ROM_WEAVER_FILE_FILTERS,\n  patchFormats: ROM_WEAVER_PATCH_FORMATS,\n  z3dsSubtypes: ROM_WEAVER_Z3DS_SUBTYPES,\n} as const;",
    )
}

fn render_command_types() -> String {
    let config = ts_rs::Config::default();
    let command_types = tagged_enum_type_literals::<Commands>(&config);
    let patch_command_types = tagged_enum_type_literals::<PatchCommands>(&config);
    let bundle_command_types = tagged_enum_type_literals::<BundleCommands>(&config);
    format!(
        "{COMMAND_TYPES_HEADER}{}\n\n{}\n\n{}\n\n{}\n",
        render_ts_const(
            "KNOWN_COMMAND_TYPES",
            Value::Array(string_values(command_types))
        ),
        render_ts_const(
            "KNOWN_PATCH_COMMAND_TYPES",
            Value::Array(string_values(patch_command_types))
        ),
        render_ts_const(
            "KNOWN_BUNDLE_COMMAND_TYPES",
            Value::Array(string_values(bundle_command_types))
        ),
        r#"export type KnownRomWeaverCommandType = typeof KNOWN_COMMAND_TYPES[number];
export type KnownRomWeaverPatchCommandType = typeof KNOWN_PATCH_COMMAND_TYPES[number];
export type KnownRomWeaverBundleCommandType = typeof KNOWN_BUNDLE_COMMAND_TYPES[number];

export function isKnownRomWeaverCommandType(value: unknown): value is KnownRomWeaverCommandType {
  return typeof value === 'string' && (KNOWN_COMMAND_TYPES as readonly string[]).includes(value);
}

export function isKnownRomWeaverPatchCommandType(value: unknown): value is KnownRomWeaverPatchCommandType {
  return typeof value === 'string' && (KNOWN_PATCH_COMMAND_TYPES as readonly string[]).includes(value);
}

export function isKnownRomWeaverBundleCommandType(value: unknown): value is KnownRomWeaverBundleCommandType {
  return typeof value === 'string' && (KNOWN_BUNDLE_COMMAND_TYPES as readonly string[]).includes(value);
}

export function assertKnownRomWeaverCommandType(
  value: unknown,
  label = 'rom-weaver command',
  field = '`type` field',
): KnownRomWeaverCommandType {
  const type = typeof value === 'string' ? value.trim() : '';
  if (!type) throw new TypeError(`${label} requires a string ${field}`);
  if (isKnownRomWeaverCommandType(type)) return type;
  throw new TypeError(`${label} has unsupported ${field}: ${type} (known: ${formatKnownTypes(KNOWN_COMMAND_TYPES)})`);
}

export function assertKnownRomWeaverPatchCommandType(
  value: unknown,
  label = 'rom-weaver patch command',
  field = '`type` field',
): KnownRomWeaverPatchCommandType {
  const type = typeof value === 'string' ? value.trim() : '';
  if (!type) throw new TypeError(`${label} requires a string ${field}`);
  if (isKnownRomWeaverPatchCommandType(type)) return type;
  throw new TypeError(`${label} has unsupported ${field}: ${type} (known: ${formatKnownTypes(KNOWN_PATCH_COMMAND_TYPES)})`);
}

export function assertKnownRomWeaverBundleCommandType(
  value: unknown,
  label = 'rom-weaver bundle command',
  field = '`type` field',
): KnownRomWeaverBundleCommandType {
  const type = typeof value === 'string' ? value.trim() : '';
  if (!type) throw new TypeError(`${label} requires a string ${field}`);
  if (isKnownRomWeaverBundleCommandType(type)) return type;
  throw new TypeError(`${label} has unsupported ${field}: ${type} (known: ${formatKnownTypes(KNOWN_BUNDLE_COMMAND_TYPES)})`);
}

function formatKnownTypes(types: readonly string[]): string {
  return types.map((type) => `"${type}"`).join(', ');
}"#,
    )
}

fn render_ts_const(name: &str, value: Value) -> String {
    let rendered = serde_json::to_string_pretty(&value).expect("metadata value should serialize");
    format!("export const {name} = {rendered} as const;")
}

fn tagged_enum_type_literals<T: TS>(config: &ts_rs::Config) -> Vec<String> {
    let decl = T::decl(config);
    let marker = "\"type\": \"";
    let mut rest = decl.as_str();
    let mut out = Vec::new();
    while let Some(start) = rest.find(marker) {
        let after_marker = &rest[start + marker.len()..];
        let Some(end) = after_marker.find('"') else {
            panic!("failed to parse ts-rs tagged enum type literal from {decl}");
        };
        out.push(after_marker[..end].to_string());
        rest = &after_marker[end + 1..];
    }
    if out.is_empty() {
        panic!("ts-rs declaration did not contain any tagged enum type literals: {decl}");
    }
    out
}

fn string_values(values: Vec<String>) -> Vec<Value> {
    values.into_iter().map(Value::String).collect()
}

fn create_patch_format_policy_value() -> Value {
    let metadata = patch_create_format_policy_metadata();
    json!({
        "defaultFormat": metadata.default_format,
        "largeDefaultFormat": metadata.large_default_format,
        "limits": {
            "archiveDefaultSizeBytes": metadata.archive_default_size_limit_bytes,
            "bpsDefaultSizeBytes": metadata.bps_default_size_limit_bytes,
            "ipsSizeLimitBytes": metadata.ips_size_limit_bytes,
            "legacySizeLimitBytes": metadata.legacy_size_limit_bytes,
        },
        "aliases": alias_map(metadata.aliases),
        "formats": {
            "small": metadata.small_formats,
            "medium": metadata.medium_formats,
            "midLarge": metadata.mid_large_formats,
            "large": metadata.large_formats,
        },
        "supportedCreateFormats": unique_formats(&[
            metadata.small_formats,
            metadata.medium_formats,
            metadata.mid_large_formats,
            metadata.large_formats,
        ]),
    })
}

fn patch_formats_value() -> Value {
    Value::Array(
        PatchRegistry::new()
            .handlers()
            .iter()
            .map(|handler| {
                let descriptor = handler.descriptor();
                let capabilities = handler.capabilities();
                json!({
                    "aliases": descriptor.aliases,
                    "capabilities": {
                        "apply": capabilities.apply,
                        "create": capabilities.create,
                        "parse": capabilities.parse,
                        "threadedDiff": capabilities.threaded_diff,
                        "threadedOutput": capabilities.threaded_output,
                        "threadedScan": capabilities.threaded_scan,
                    },
                    "extensions": descriptor.extensions,
                    "label": descriptor.name,
                    "magic": handler.header_magic().unwrap_or_default(),
                    "name": patch_format_command_name(descriptor.name, descriptor.aliases),
                })
            })
            .collect(),
    )
}

fn patch_format_command_name(name: &str, aliases: &[&str]) -> String {
    let normalized_name = name.trim().to_ascii_lowercase();
    if is_patch_command_token(&normalized_name) {
        return normalized_name;
    }
    aliases
        .iter()
        .map(|alias| alias.trim().to_ascii_lowercase())
        .find(|alias| is_patch_command_token(alias))
        .unwrap_or(normalized_name)
}

fn is_patch_command_token(value: &str) -> bool {
    !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
}

fn file_filters_value() -> Value {
    json!({
        "containerExtensions": CONTAINER_FILTER_FILE_EXTENSIONS,
        "patchExtensions": PATCH_FILTER_FILE_EXTENSIONS,
        "romExtensions": ROM_FILTER_FILE_EXTENSIONS,
    })
}

fn compression_metadata_value() -> Value {
    let metadata = compression_metadata();
    let mut codecs = Map::new();
    for codec in metadata.codecs {
        codecs.insert(
            codec.name.to_string(),
            json!({
                "aliases": codec.aliases,
                "level": codec
                    .level
                    .map(|level| json!({ "min": level.min, "max": level.max }))
                    .unwrap_or(Value::Null),
                "profileKind": codec.profile_kind,
            }),
        );
    }

    let mut codec_fields = Map::new();
    for field in metadata.codec_fields {
        codec_fields.insert(
            field.name.to_string(),
            json!({
                "allowMultiple": field.allow_multiple,
                "codecs": field.codecs,
                "defaultCodec": field.default_codec,
                "defaultCodecs": field.default_codecs,
                "presets": field
                    .presets
                    .iter()
                    .map(|preset| json!({ "codecs": preset.codecs, "kind": preset.kind }))
                    .collect::<Vec<_>>(),
            }),
        );
    }

    json!({
        "codecFields": Value::Object(codec_fields),
        "codecs": Value::Object(codecs),
        "defaults": {
            "chdCreateCdCodecs": metadata.defaults.chd_create_cd_codecs,
            "chdCreateDvdCodecs": metadata.defaults.chd_create_dvd_codecs,
            "rvzBlockSize": metadata.defaults.rvz_block_size,
            "rvzCodec": metadata.defaults.rvz_codec,
            "rvzCompressionLevel": metadata.defaults.rvz_compression_level,
            "sevenZipCodec": metadata.defaults.seven_zip_codec,
            "zipCodec": metadata.defaults.zip_codec,
            "z3dsCodec": metadata.defaults.z3ds_codec,
        },
        "profiles": metadata
            .profiles
            .iter()
            .map(|profile| json!({
                "label": profile.label,
                "name": profile.name,
                "standardLevel": profile.standard_level,
                "zstdLevel": profile.zstd_level,
            }))
            .collect::<Vec<_>>(),
    })
}

fn container_formats_value() -> Value {
    Value::Array(
        container_format_metadata()
            .into_iter()
            .map(container_format_value)
            .collect(),
    )
}

fn container_format_value(metadata: ContainerFormatMetadata) -> Value {
    json!({
        "name": metadata.name,
        "aliases": metadata.aliases,
        "extensions": metadata.extensions,
        "capabilities": {
            "probeDetails": metadata.capabilities.probe_details,
            "extract": metadata.capabilities.extract,
            "create": metadata.capabilities.create,
            "extractThreads": thread_capability_value(metadata.capabilities.extract_threads),
            "createThreads": thread_capability_value(metadata.capabilities.create_threads),
        },
        "defaultOutput": metadata
            .default_output
            .map(container_default_output_value)
            .unwrap_or(Value::Null),
        "magic": metadata.magic,
    })
}

fn disc_image_policy_value() -> Value {
    let metadata = disc_image_policy_metadata();
    json!({
        "cdSectorSizes": metadata.cd_sector_sizes,
        "ambiguousDiscImageExtensions": metadata.ambiguous_disc_image_extensions,
    })
}

fn archive_extension_alias_value(alias: ArchiveExtensionAlias) -> Value {
    json!({
        "extension": alias.extension,
        "archiveType": alias.archive_type,
    })
}

fn archive_formats_value() -> Value {
    let metadata: ArchiveFormatMetadata = archive_format_metadata();
    json!({
        "magicSignatures": metadata
            .magic_signatures
            .iter()
            .map(|signature| json!({
                "bytes": signature.bytes,
                "offset": signature.offset,
                "archiveType": signature.archive_type,
            }))
            .collect::<Vec<_>>(),
        "extensionAliases": metadata
            .extension_aliases
            .iter()
            .map(|alias| archive_extension_alias_value(*alias))
            .collect::<Vec<_>>(),
        "multipartExtensionAliases": metadata
            .multipart_extension_aliases
            .iter()
            .map(|alias| archive_extension_alias_value(*alias))
            .collect::<Vec<_>>(),
        "multipartExtensions": metadata.multipart_extensions,
        "supportedExtensions": metadata.supported_extensions,
    })
}

fn z3ds_subtypes_value() -> Value {
    Value::Array(
        z3ds_subtype_metadata()
            .iter()
            .map(|subtype| {
                json!({
                    "underlyingExtension": subtype.underlying_extension,
                    "underlyingAliases": subtype.underlying_aliases,
                    "compressedExtension": subtype.compressed_extension,
                    "underlyingMagic": subtype.underlying_magic.map(|magic| magic.to_vec()),
                })
            })
            .collect(),
    )
}

fn thread_capability_value(metadata: ContainerThreadCapabilityMetadata) -> Value {
    json!({
        "parallel": metadata.parallel,
        "maxThreads": metadata.max_threads,
    })
}

fn container_default_output_value(metadata: ContainerDefaultOutputMetadata) -> Value {
    json!({
        "format": metadata.format,
        "label": metadata.label,
        "outputExtension": metadata.output_extension,
        "outputExtensionStrategy": output_extension_strategy_name(metadata.output_extension_strategy),
        "automaticParentKinds": metadata.automatic_parent_kinds,
        "automaticSourceExtensions": metadata.automatic_source_extensions,
        "compressionInputExtensions": metadata.compression_input_extensions,
        "decompressionInputExtensions": metadata.decompression_input_extensions,
    })
}

fn output_extension_strategy_name(strategy: ContainerOutputExtensionStrategy) -> &'static str {
    match strategy {
        ContainerOutputExtensionStrategy::Append => "append",
        ContainerOutputExtensionStrategy::Replace => "replace",
        ContainerOutputExtensionStrategy::Z3dsSubtype => "z3ds-subtype",
    }
}

fn container_format_aliases_value() -> Value {
    let mut out = Map::new();
    for metadata in container_format_metadata() {
        for alias in metadata.aliases {
            out.insert(
                (*alias).to_string(),
                Value::String(metadata.name.to_string()),
            );
        }
    }
    Value::Object(out)
}

fn create_container_formats_value() -> Value {
    Value::Array(
        container_format_metadata()
            .into_iter()
            .filter(|metadata| metadata.capabilities.create)
            .map(|metadata| Value::String(metadata.name.to_string()))
            .collect(),
    )
}

fn alias_map(aliases: &[(&'static str, &'static str)]) -> Value {
    let mut out = Map::new();
    for (alias, canonical) in aliases {
        out.insert(
            (*alias).to_string(),
            Value::String((*canonical).to_string()),
        );
    }
    Value::Object(out)
}

fn unique_formats(groups: &[&[&'static str]]) -> Vec<&'static str> {
    let mut out = Vec::new();
    for group in groups {
        for format in *group {
            if !out.contains(format) {
                out.push(*format);
            }
        }
    }
    out
}
